// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"
#include "log.h"

static const char *TAG = "ui_device_id_reg_Screen";
static int device_id = 0;
extern bool device_id_check_flag;

static void mbox_device_id_err_event_cb(lv_event_t *e) {
  lv_obj_t *obj = lv_event_get_current_target(e);
  LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
  if (strcmp(lv_msgbox_get_active_btn_text(obj), "Close") == 0) {
    lv_msgbox_close(obj);
  }
}

void ui_device_id_Delete_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t *ta = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED) {
    lv_textarea_set_text(ta, "\0");
  }
}

void ui_device_id_Comfirm_Btn_e_hendler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
    lv_label_set_text_fmt(ui_main_scr_Device_Id_Area_Label, "%03d", device_id);
  }
}

void ui_device_id_Register_Btn_e_hendler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  lv_obj_t *ta = lv_event_get_user_data(e);
  char s_deivce_id[30] = { 0 };
  int ret;
  if (event_code == LV_EVENT_CLICKED) {
    lv_event_send(ta, LV_EVENT_READY, NULL);
    // Max 999
    if (device_id >= 1000) {
      LOGI(TAG, "device id is over number!!  ");
      static const char *btns[] = { "Close", "" };
      lv_obj_t *mbox_device_id_err_1 = lv_msgbox_create(NULL, "Oops!", "Available from 1 to 999", btns, true);
      lv_obj_add_event_cb(mbox_device_id_err_1, mbox_device_id_err_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
      lv_obj_center(mbox_device_id_err_1);
    } else {
      snprintf(s_deivce_id, sizeof(s_deivce_id), "%03d", device_id);
      LOGI(TAG, "Device id : %s", s_deivce_id);
      ret = syscfg_set(CFG_DATA, "DEVICE_ID", s_deivce_id);
      if (ret) {
        LOGI(TAG, "Register fail ");
        static const char *btns[] = { "Close", "" };
        lv_obj_t *mbox_device_id_err_2 = lv_msgbox_create(NULL, "Oops!", "Register fail!", btns, true);
        lv_obj_add_event_cb(mbox_device_id_err_2, mbox_device_id_err_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
        lv_obj_center(mbox_device_id_err_2);
      } else {
        device_id_check_flag = true;
        LOGI(TAG, "Device ID registration successful ");
        static const char *btns[] = { "Close", "" };
        lv_obj_t *mbox_device_id = lv_msgbox_create(NULL, "Success!", "Registered!", btns, true);
        lv_obj_add_event_cb(mbox_device_id, mbox_device_id_err_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
        lv_obj_center(mbox_device_id);
      }
    }
  }
}

void ui_device_id_Taxtarea_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *ta = lv_event_get_target(e);
  if (code == LV_EVENT_READY) {
    device_id = atoi(lv_textarea_get_text(ta));
    // sscanf(lv_textarea_get_text(ta), "%f", &device_id);
    LOGI(TAG, "Enter was pressed. The current text is: %d", device_id);
  }
  /*Todo : */
}

void ui_device_id_btnm_event_handler(lv_event_t *e) {
  lv_obj_t *obj = lv_event_get_target(e);
  lv_obj_t *ta = lv_event_get_user_data(e);
  const char *txt = lv_btnmatrix_get_btn_text(obj, lv_btnmatrix_get_selected_btn(obj));
  if (strcmp(txt, "C") == 0)
    lv_textarea_del_char(ta);
  else if (strcmp(txt, LV_SYMBOL_NEW_LINE) == 0)
    lv_event_send(ta, LV_EVENT_READY, NULL);
  else
    lv_textarea_add_text(ta, txt);
}

void ui_device_id_reg_screen_init(void) {
  ui_device_id_reg_screen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_device_id_reg_screen, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  lv_obj_t *ui_device_id_Taxtarea = lv_textarea_create(ui_device_id_reg_screen);
  lv_textarea_set_one_line(ui_device_id_Taxtarea, true);
  lv_obj_set_width(ui_device_id_Taxtarea, 125);  /// 1
  lv_obj_set_height(ui_device_id_Taxtarea, 40);  /// 1
  lv_obj_align(ui_device_id_Taxtarea, LV_ALIGN_TOP_MID, -130, 10);
  lv_obj_add_event_cb(ui_device_id_Taxtarea, ui_device_id_Taxtarea_e_handler, LV_EVENT_READY, NULL);
  lv_obj_add_state(ui_device_id_Taxtarea, LV_STATE_DEFAULT); /*To be sure the cursor is visible*/

  lv_obj_t *ui_device_id_Register_Btn = lv_btn_create(ui_device_id_reg_screen);
  lv_obj_set_width(ui_device_id_Register_Btn, 70);
  lv_obj_set_height(ui_device_id_Register_Btn, 50);
  lv_obj_set_x(ui_device_id_Register_Btn, -190);
  lv_obj_set_y(ui_device_id_Register_Btn, 65);
  lv_obj_set_align(ui_device_id_Register_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_device_id_Register_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_device_id_Register_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_device_id_Register_Btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_device_id_Register_Btn, ui_device_id_Register_Btn_e_hendler, LV_EVENT_ALL,
                      ui_device_id_Taxtarea);

  lv_obj_t *ui_device_id_Register_Btn_Label = lv_label_create(ui_device_id_Register_Btn);
  lv_obj_set_width(ui_device_id_Register_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_device_id_Register_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_device_id_Register_Btn_Label, -3);
  lv_obj_set_y(ui_device_id_Register_Btn_Label, 1);
  lv_label_set_text(ui_device_id_Register_Btn_Label, "등 록");
  lv_obj_set_style_text_font(ui_device_id_Register_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_device_id_Comfirm_Btn = lv_btn_create(ui_device_id_reg_screen);
  lv_obj_set_width(ui_device_id_Comfirm_Btn, 70);
  lv_obj_set_height(ui_device_id_Comfirm_Btn, 50);
  lv_obj_set_x(ui_device_id_Comfirm_Btn, -190);
  lv_obj_set_y(ui_device_id_Comfirm_Btn, 125);
  lv_obj_set_align(ui_device_id_Comfirm_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_device_id_Comfirm_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_device_id_Comfirm_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_device_id_Comfirm_Btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_device_id_Comfirm_Btn, ui_device_id_Comfirm_Btn_e_hendler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_device_id_Comfirm_Btn_Label = lv_label_create(ui_device_id_Comfirm_Btn);
  lv_obj_set_width(ui_device_id_Comfirm_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_device_id_Comfirm_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_device_id_Comfirm_Btn_Label, -3);
  lv_obj_set_y(ui_device_id_Comfirm_Btn_Label, 1);
  lv_label_set_text(ui_device_id_Comfirm_Btn_Label, "완 료");
  lv_obj_set_style_text_font(ui_device_id_Comfirm_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_device_id_Delete_Btn = lv_btn_create(ui_device_id_reg_screen);
  lv_obj_set_width(ui_device_id_Delete_Btn, 70);
  lv_obj_set_height(ui_device_id_Delete_Btn, 50);
  lv_obj_set_x(ui_device_id_Delete_Btn, -110);
  lv_obj_set_y(ui_device_id_Delete_Btn, 125);
  lv_obj_set_align(ui_device_id_Delete_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_device_id_Delete_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_device_id_Delete_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_device_id_Delete_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_device_id_Delete_Btn, ui_device_id_Delete_Btn_e_handler, LV_EVENT_ALL, ui_device_id_Taxtarea);

  lv_obj_t *ui_device_id_Delete_Btn_Label = lv_label_create(ui_device_id_Delete_Btn);
  lv_obj_set_width(ui_device_id_Delete_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_device_id_Delete_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_device_id_Delete_Btn_Label, -3);
  lv_obj_set_y(ui_device_id_Delete_Btn_Label, 1);
  lv_label_set_text(ui_device_id_Delete_Btn_Label, "삭 제");
  lv_obj_set_style_text_font(ui_device_id_Delete_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  static const char *btnm_map[] = { "1", "2", "3", "\n", "4", "5", "6", "\n", "7", "8", "9", "\n", "C", "0", ".", "" };

  lv_obj_t *ui_device_id_Btnm = lv_btnmatrix_create(ui_device_id_reg_screen);
  lv_obj_set_size(ui_device_id_Btnm, 300, 320);
  lv_obj_align(ui_device_id_Btnm, LV_ALIGN_BOTTOM_RIGHT, 0, 0);
  lv_obj_set_style_text_font(ui_device_id_Btnm, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_device_id_Btnm, ui_device_id_btnm_event_handler, LV_EVENT_VALUE_CHANGED,
                      ui_device_id_Taxtarea);
  lv_obj_clear_flag(ui_device_id_Btnm, LV_OBJ_FLAG_CLICK_FOCUSABLE); /*To keep the text area focused on button clicks*/
  lv_btnmatrix_set_map(ui_device_id_Btnm, btnm_map);

  lv_obj_t *ui_device_id_Label = lv_label_create(ui_device_id_reg_screen);
  lv_obj_set_width(ui_device_id_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_device_id_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_device_id_Label, -215);
  lv_obj_set_y(ui_device_id_Label, 20);
  lv_obj_set_align(ui_device_id_Label, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_device_id_Label, "기기명");
  lv_obj_set_style_text_font(ui_device_id_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
}
