// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"

void ui_list_select_screen_init(void) {
  ui_list_select = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_list_select, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_ListPanel = lv_obj_create(ui_list_select);
  lv_obj_set_width(ui_ListPanel, 450);
  lv_obj_set_height(ui_ListPanel, 250);
  lv_obj_set_x(ui_ListPanel, 0);
  lv_obj_set_y(ui_ListPanel, 30);
  lv_obj_set_scroll_snap_x(ui_ListPanel, LV_SCROLL_SNAP_CENTER);
  lv_obj_set_scroll_dir(ui_ListPanel, LV_DIR_VER);  // only scroll vertically
  lv_obj_set_flex_flow(ui_ListPanel, LV_FLEX_FLOW_ROW_WRAP);
  lv_obj_set_align(ui_ListPanel, LV_ALIGN_CENTER);
  // lv_obj_clear_flag(ui_ListPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_ListDiscPanel = lv_obj_create(ui_list_select);
  lv_obj_set_width(ui_ListDiscPanel, 333);
  lv_obj_set_height(ui_ListDiscPanel, 40);
  lv_obj_set_x(ui_ListDiscPanel, 57);
  lv_obj_set_y(ui_ListDiscPanel, -122);
  lv_obj_set_align(ui_ListDiscPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_ListDiscPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_ListDiscPanelLabel = lv_label_create(ui_ListDiscPanel);
  lv_obj_set_width(ui_ListDiscPanelLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_ListDiscPanelLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_ListDiscPanelLabel, LV_ALIGN_LEFT_MID);
  lv_label_set_long_mode(ui_ListDiscPanelLabel, LV_LABEL_LONG_SCROLL);
  lv_label_set_text(ui_ListDiscPanelLabel, "1. upper: 20, lower: 20");

  ui_LisPordNumPanel = lv_obj_create(ui_list_select);
  lv_obj_set_width(ui_LisPordNumPanel, 90);
  lv_obj_set_height(ui_LisPordNumPanel, 40);
  lv_obj_set_x(ui_LisPordNumPanel, -179);
  lv_obj_set_y(ui_LisPordNumPanel, -122);
  lv_obj_set_align(ui_LisPordNumPanel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_LisPordNumPanel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_LisPordNumPanelLabel = lv_label_create(ui_LisPordNumPanel);
  lv_obj_set_width(ui_LisPordNumPanelLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_LisPordNumPanelLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_LisPordNumPanelLabel, LV_ALIGN_LEFT_MID);
  lv_label_set_long_mode(ui_LisPordNumPanelLabel, LV_LABEL_LONG_SCROLL);
  lv_label_set_text(ui_LisPordNumPanelLabel, "12");

  ui_ListPanelBtn = lv_btn_create(ui_list_select);
  lv_obj_set_width(ui_ListPanelBtn, 80);
  lv_obj_set_height(ui_ListPanelBtn, 40);
  lv_obj_set_x(ui_ListPanelBtn, 185);
  lv_obj_set_y(ui_ListPanelBtn, -122);
  lv_obj_set_align(ui_ListPanelBtn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ListPanelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_ListPanelBtn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

  ui_ListPanelBtnLabel = lv_label_create(ui_ListPanelBtn);
  lv_obj_set_width(ui_ListPanelBtnLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_ListPanelBtnLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_ListPanelBtnLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ListPanelBtnLabel, "ok");

  lv_obj_add_event_cb(ui_ListPanelBtn, ui_event_ListPanelBtn, LV_EVENT_ALL, NULL);
}
