// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"
#include "log.h"

static const char *TAG = "  ui_mode_1_main_Screen";

extern custom_msg_box_t *user_data_obj;
extern void Msg_Box_No_Btn_e_handler(lv_event_t *e);
extern void memory_allocation_manger();
extern void create_custom_msg_box(const char *msg_text, lv_obj_t *active_screen, void (*event_handler)(lv_event_t *),
                                  lv_event_code_t event);

static lv_anim_t animation_template;
static lv_style_t label_style;

void ui_Screen1_Setting_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen2_screen_init);
  }
}
void ui_Screen1_Mode_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  int res = 0;
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
  }
}
void ui_Screen1_Prod_Num_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "품번 %02d", prod_num_value);
    lv_label_set_text(target, s_buff);
  }
}

void ui_Screen1_Upper_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    if (prod_num_value == 0) {
      snprintf(s_buff, sizeof(s_buff), "판정하지않습니다.");
      lv_label_set_text(target, s_buff);
    } else {
      snprintf(s_buff, sizeof(s_buff), "상한 %.3f", upper_weight_value);
      lv_label_set_text(target, s_buff);
    }
  }
}

void ui_Screen1_Lower_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    if (prod_num_value == 0) {
      lv_label_set_text(target, s_buff);
    } else {
      snprintf(s_buff, sizeof(s_buff), "하한 %.3f", lower_weight_value);
      lv_label_set_text(target, s_buff);
    }
  }
}

void ui_Screen1_Amount_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "min:100g");
    // lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

// static void Judge_Comfirm_Btn_mbox_event_cb(lv_event_t *e) {
//   lv_obj_t *obj = lv_event_get_current_target(e);
//   LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
//   if (strcmp(lv_msgbox_get_active_btn_text(obj), "Yes") == 0) {
//     FDATA_TABLE_INDEX(log_table_index, BASE_PATH, "%d,%d,%d,%d,%d", *ui_data_ctx.ptr[0], *ui_data_ctx.ptr[1],
//                       *ui_data_ctx.ptr[2], *ui_data_ctx.ptr[3], *ui_data_ctx.ptr[4]);
//     *ui_data_ctx.ptr[1] = 0;  // judge_total_count initialize.
//     *ui_data_ctx.ptr[2] = 0;  // judge_over_count initialize.
//     *ui_data_ctx.ptr[3] = 0;  // judge_normal_countinitialize.
//     *ui_data_ctx.ptr[4] = 0;  // judge_lack_count initialize.
//     lv_label_set_text(ui_Screen1_over_Label, "초 과");
//     lv_label_set_text(ui_Screen1_normal_Label, "정 상");
//     lv_label_set_text(ui_Screen1_lack_Label, "부 족");
//     ui_data_ctx.ids = JUDGE_COMFIRM_E;
//     lv_msgbox_close(obj);
//   } else {
//     lv_msgbox_close(obj);
//   }
// }

static void Judge_Comfirm_Btn_Yes_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  custom_msg_box_t *user_data_obj = lv_event_get_user_data(e);
  // LOGI(TAG, "Click Judge_Comfirm_Btn_Yes_event_cb!!");
  if (code == LV_EVENT_CLICKED) {
    FDATA_TABLE_INDEX(log_table_index, BASE_PATH, "%d,%d,%d,%d,%d", *ui_data_ctx.ptr[0], *ui_data_ctx.ptr[1],
                      *ui_data_ctx.ptr[2], *ui_data_ctx.ptr[3], *ui_data_ctx.ptr[4]);
    *ui_data_ctx.ptr[1] = 0;  // judge_total_count initialize.
    *ui_data_ctx.ptr[2] = 0;  // judge_over_count initialize.
    *ui_data_ctx.ptr[3] = 0;  // judge_normal_countinitialize.
    *ui_data_ctx.ptr[4] = 0;  // judge_lack_count initialize.
    lv_label_set_text(ui_Screen1_over_Label, "초 과");
    lv_label_set_text(ui_Screen1_normal_Label, "정 상");
    lv_label_set_text(ui_Screen1_lack_Label, "부 족");
    ui_data_ctx.ids = JUDGE_COMFIRM_E;
    memory_allocation_manger();
  } else {
    memory_allocation_manger();
  }
}

void ui_Screen1_Judge_Comfirm_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  if (code == LV_EVENT_CLICKED) {
    create_custom_msg_box("작업을 완료할가요?", ui_Screen1, Judge_Comfirm_Btn_Yes_event_cb, LV_EVENT_CLICKED);
  }
}

// static void Judge_Cancel_Btn_mbox_event_cb(lv_event_t *e) {
//   lv_obj_t *obj = lv_event_get_current_target(e);
//   LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
//   if (strcmp(lv_msgbox_get_active_btn_text(obj), "Yes") == 0) {
//     *ui_data_ctx.ptr[1] = 0;  // judge_total_count initialize.
//     *ui_data_ctx.ptr[2] = 0;  // judge_over_count initialize.
//     *ui_data_ctx.ptr[3] = 0;  // judge_normal_countinitialize.
//     *ui_data_ctx.ptr[4] = 0;  // judge_lack_count initialize.
//     lv_label_set_text(ui_Screen1_over_Label, "초 과");
//     lv_label_set_text(ui_Screen1_normal_Label, "정 상");
//     lv_label_set_text(ui_Screen1_lack_Label, "부 족");

//     while (!isEmpty(ui_data_ctx.stack_root)) {
//       // Stack remove
//       LOGI(TAG, "Top element is %d\n", peek(ui_data_ctx.stack_root));
//       pop(&ui_data_ctx.stack_root);
//     }

//     lv_msgbox_close(obj);
//   } else {
//     lv_msgbox_close(obj);
//   }
// }

static void Judge_Cancel_Btn_Yes_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  custom_msg_box_t *user_data_obj = lv_event_get_user_data(e);
  // LOGI(TAG, "click Judge_Cancel_Btn_Yes_event_cb!!");
  if (code == LV_EVENT_CLICKED) {
    *ui_data_ctx.ptr[1] = 0;  // judge_total_count initialize.
    *ui_data_ctx.ptr[2] = 0;  // judge_over_count initialize.
    *ui_data_ctx.ptr[3] = 0;  // judge_normal_countinitialize.
    *ui_data_ctx.ptr[4] = 0;  // judge_lack_count initialize.
    lv_label_set_text(ui_Screen1_over_Label, "초 과");
    lv_label_set_text(ui_Screen1_normal_Label, "정 상");
    lv_label_set_text(ui_Screen1_lack_Label, "부 족");

    while (!isEmpty(ui_data_ctx.stack_root)) {
      // Stack remove
      LOGI(TAG, "Top element is %d free memory\n", peek(ui_data_ctx.stack_root));
      pop(&ui_data_ctx.stack_root);
    }
    memory_allocation_manger();
  } else {
    LOGI(TAG, "Miss loop Judge_Cancel_Btn_Yes_event_cb ");
    memory_allocation_manger();
  }
}

static void ui_Screen1_Judge_Cancel_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  if (code == LV_EVENT_CLICKED) {
    create_custom_msg_box("전체작업을 취소할가요?\n저장되지 않습니다.", ui_Screen1, Judge_Cancel_Btn_Yes_event_cb,
                          LV_EVENT_CLICKED);
  }
}

// static void Recently_Cancel_Btn_mbox_event_cb(lv_event_t *e) {
//   lv_obj_t *obj = lv_event_get_current_target(e);
//   LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
//   if (strcmp(lv_msgbox_get_active_btn_text(obj), "Yes") == 0) {
//     *ui_data_ctx.ptr[1] = *ui_data_ctx.ptr[1] - 1;  // Decrease/reduce total count
//     if (peek(ui_data_ctx.stack_root) == JUDGE_LACK) {
//       LOGI(TAG, "JUDGE_LACK Top element is %d\n", peek(ui_data_ctx.stack_root));
//       *ui_data_ctx.ptr[4] = *ui_data_ctx.ptr[4] - 1;
//       lv_label_set_text_fmt(ui_Screen1_lack_Label, "부족 %d", *ui_data_ctx.ptr[4]);
//       pop(&ui_data_ctx.stack_root);
//       lv_msgbox_close(obj);
//     } else if (peek(ui_data_ctx.stack_root) == JUDGE_NORMAL) {
//       LOGI(TAG, "JUDGE_NORMAL Top element is %d\n", peek(ui_data_ctx.stack_root));
//       *ui_data_ctx.ptr[3] = *ui_data_ctx.ptr[3] - 1;
//       lv_label_set_text_fmt(ui_Screen1_normal_Label, "정상 %d", *ui_data_ctx.ptr[3]);
//       pop(&ui_data_ctx.stack_root);
//       lv_msgbox_close(obj);
//     } else if (peek(ui_data_ctx.stack_root) == JUDGE_OVER) {
//       LOGI(TAG, "JUDGE_OVER Top element is %d\n", peek(ui_data_ctx.stack_root));
//       *ui_data_ctx.ptr[2] = *ui_data_ctx.ptr[2] - 1;
//       lv_label_set_text_fmt(ui_Screen1_over_Label, "초과 %d", *ui_data_ctx.ptr[2]);
//       pop(&ui_data_ctx.stack_root);
//       lv_msgbox_close(obj);
//     } else {
//       LOGI(TAG, "Empty stack!!");
//     }
//   } else {
//     lv_msgbox_close(obj);
//   }
// }

static void Recently_Cancel_Btn_Yes_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  // custom_msg_box_t *user_data_obj = lv_event_get_user_data(e);
  // LOGI(TAG, "click btn Msg_Box_Yes_Btn_e_handler!!");
  if (code == LV_EVENT_CLICKED) {
    // LOGI(TAG, "click btn!!");
    if (peek(ui_data_ctx.stack_root) == JUDGE_LACK) {
      LOGI(TAG, "JUDGE_LACK Top element is %d\n", peek(ui_data_ctx.stack_root));
      *ui_data_ctx.ptr[1] = *ui_data_ctx.ptr[1] - 1;  // Decrease/reduce total count
      *ui_data_ctx.ptr[4] = *ui_data_ctx.ptr[4] - 1;
      lv_label_set_text_fmt(ui_Screen1_lack_Label, "부족 %d", *ui_data_ctx.ptr[4]);
      pop(&ui_data_ctx.stack_root);
      memory_allocation_manger();
    } else if (peek(ui_data_ctx.stack_root) == JUDGE_NORMAL) {
      LOGI(TAG, "JUDGE_NORMAL Top element is %d\n", peek(ui_data_ctx.stack_root));
      *ui_data_ctx.ptr[1] = *ui_data_ctx.ptr[1] - 1;  // Decrease/reduce total count
      *ui_data_ctx.ptr[3] = *ui_data_ctx.ptr[3] - 1;
      lv_label_set_text_fmt(ui_Screen1_normal_Label, "정상 %d", *ui_data_ctx.ptr[3]);
      pop(&ui_data_ctx.stack_root);
      memory_allocation_manger();
    } else if (peek(ui_data_ctx.stack_root) == JUDGE_OVER) {
      LOGI(TAG, "JUDGE_OVER Top element is %d\n", peek(ui_data_ctx.stack_root));
      *ui_data_ctx.ptr[1] = *ui_data_ctx.ptr[1] - 1;  // Decrease/reduce total count
      *ui_data_ctx.ptr[2] = *ui_data_ctx.ptr[2] - 1;
      lv_label_set_text_fmt(ui_Screen1_over_Label, "초과 %d", *ui_data_ctx.ptr[2]);
      pop(&ui_data_ctx.stack_root);
      memory_allocation_manger();
    } else {
      lv_label_set_text(user_data_obj->target2, "직전작업이 없습니다.");
      LOGI(TAG, "Empty stack!!");
    }
  }
}

static void ui_Screen1_Recently_Cancel_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  // LOGI(TAG, "click btn ui_Screen1_Recently_Cancel_Btn_e_handler!!");
  if (code == LV_EVENT_CLICKED) {
    create_custom_msg_box("직전작업을 취소할까요?", ui_Screen1, Recently_Cancel_Btn_Yes_e_handler, LV_EVENT_CLICKED);
  }
}

void ui_Screen1_Zero_Point_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  int ret = 0;
  if (event_code == LV_EVENT_CLICKED) {
    ret = weight_zero_command();
  }
}

void ui_Screen1_Tare_Point_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  int ret = 0;
  if (event_code == LV_EVENT_CLICKED) {
    memset(s_tare_set_value, 0x00, sizeof(s_tare_set_value));
    ret = cas_tare_command(s_tare_set_value);
  }
}

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  /* screen1 leds*/
  ui_led1 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led1, LV_ALIGN_TOP_LEFT, 30, 35);
  lv_led_set_brightness(ui_led1, LV_LED_BRIGHT_MAX);
  lv_led_set_color(ui_led1, lv_palette_main(LV_PALETTE_YELLOW));
  lv_led_off(ui_led1);

  ui_led2 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led2, LV_ALIGN_TOP_LEFT, 95, 35);
  lv_led_set_brightness(ui_led2, LV_LED_BRIGHT_MAX);
  lv_led_set_color(ui_led2, lv_palette_main(LV_PALETTE_LIGHT_GREEN));
  lv_led_off(ui_led2);

  ui_led3 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led3, LV_ALIGN_TOP_LEFT, 160, 35);
  lv_led_set_brightness(ui_led3, LV_LED_BRIGHT_MAX);
  lv_led_set_color(ui_led3, lv_palette_main(LV_PALETTE_RED));
  lv_led_off(ui_led3);

  ui_Screen1_over_Label = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_over_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_over_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_over_Label, 29);
  lv_obj_set_y(ui_Screen1_over_Label, 10);
  lv_obj_set_align(ui_Screen1_over_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_over_Label, "초 과");
  lv_obj_set_style_text_font(ui_Screen1_over_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_normal_Label = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_normal_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_normal_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_normal_Label, 95);
  lv_obj_set_y(ui_Screen1_normal_Label, 10);
  lv_obj_set_align(ui_Screen1_normal_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_normal_Label, "정 상");
  lv_obj_set_style_text_font(ui_Screen1_normal_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_lack_Label = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_lack_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_lack_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_lack_Label, 159);
  lv_obj_set_y(ui_Screen1_lack_Label, 10);
  lv_obj_set_align(ui_Screen1_lack_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_lack_Label, "부 족");
  lv_obj_set_style_text_font(ui_Screen1_lack_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  /* Screen1 main panel*/
  ui_Panel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel1, 392);
  lv_obj_set_height(ui_Panel1, 173);
  lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_Screen1_Panel1_Current_Weight_Label = lv_label_create(ui_Panel1);         // weight display
  lv_obj_set_width(ui_Screen1_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Current_Weight_Label, 15);
  lv_obj_set_y(ui_Screen1_Panel1_Current_Weight_Label, 10);
  lv_label_set_text(ui_Screen1_Panel1_Current_Weight_Label, "0000");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Current_Weight_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Current_Count_Label = lv_label_create(ui_Panel1);         // count display
  lv_obj_set_width(ui_Screen1_Panel1_Current_Count_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Current_Count_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Current_Count_Label, 240);
  lv_obj_set_y(ui_Screen1_Panel1_Current_Count_Label, 10);
  lv_label_set_text(ui_Screen1_Panel1_Current_Count_Label, "000");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Current_Count_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Zero_Point_Label = lv_label_create(ui_Panel1);         // zero display
  lv_obj_set_width(ui_Screen1_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Zero_Point_Label, 5);
  lv_obj_set_y(ui_Screen1_Panel1_Zero_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Zero_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Zero_Point_Label, "영점");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Zero_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Zero_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Zero_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Stable_Point_Label = lv_label_create(ui_Panel1);         // // stable display
  lv_obj_set_width(ui_Screen1_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Stable_Point_Label, 50);
  lv_obj_set_y(ui_Screen1_Panel1_Stable_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Stable_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Stable_Point_Label, "안정");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Stable_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Stable_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Stable_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Tare_Point_Label = lv_label_create(ui_Panel1);         // // stable display
  lv_obj_set_width(ui_Screen1_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Tare_Point_Label, 95);
  lv_obj_set_y(ui_Screen1_Panel1_Tare_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Tare_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Tare_Point_Label, "용기");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Tare_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Tare_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Tare_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label_total_amount = lv_label_create(ui_Panel1);  // 총수량
  lv_obj_set_width(ui_Label_total_amount, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_height(ui_Label_total_amount, LV_SIZE_CONTENT);     /// 1
  lv_obj_set_x(ui_Label_total_amount, -30);
  lv_obj_set_y(ui_Label_total_amount, 0);
  lv_obj_set_align(ui_Label_total_amount, LV_ALIGN_TOP_RIGHT);
  lv_label_set_text(ui_Label_total_amount, "총수량");
  lv_obj_set_style_text_font(ui_Label_total_amount, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Prod_Num_Label = lv_label_create(ui_Panel1);         // 총수량
  lv_obj_set_width(ui_Screen1_Prod_Num_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Prod_Num_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Prod_Num_Label, -135);
  lv_obj_set_y(ui_Screen1_Prod_Num_Label, 0);
  lv_obj_set_align(ui_Screen1_Prod_Num_Label, LV_ALIGN_TOP_RIGHT);
  lv_label_set_text(ui_Screen1_Prod_Num_Label, "품번");
  lv_obj_set_style_text_font(ui_Screen1_Prod_Num_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Prod_Num_Label, ui_Screen1_Prod_Num_Label_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Upper_Value_Label = lv_label_create(ui_Panel1);         // 상한값 표시
  lv_obj_set_width(ui_Screen1_Upper_Value_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Upper_Value_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Upper_Value_Label, 5);
  lv_obj_set_y(ui_Screen1_Upper_Value_Label, 5);
  lv_obj_set_align(ui_Screen1_Upper_Value_Label, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_Screen1_Upper_Value_Label, "상한");
  lv_obj_set_style_text_font(ui_Screen1_Upper_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Upper_Value_Label, ui_Screen1_Upper_Value_Label_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Lower_Value_Label = lv_label_create(ui_Panel1);         // 하한값 표시
  lv_obj_set_width(ui_Screen1_Lower_Value_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Lower_Value_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Lower_Value_Label, 115);
  lv_obj_set_y(ui_Screen1_Lower_Value_Label, 5);
  lv_obj_set_align(ui_Screen1_Lower_Value_Label, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_Screen1_Lower_Value_Label, "하한");
  lv_obj_set_style_text_font(ui_Screen1_Lower_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Lower_Value_Label, ui_Screen1_Lower_Value_Label_e_handler, LV_EVENT_ALL, NULL);

  /* added animation */
  lv_anim_init(&animation_template);
  lv_anim_set_delay(&animation_template, 1000); /*Wait 1 second to start the first scroll*/
  lv_anim_set_repeat_delay(&animation_template,
                           3000); /*Repeat the scroll 3 seconds after the label scrolls back to the initial position*/

  /*Initialize the label style with the animation template*/
  lv_style_init(&label_style);
  lv_style_set_anim(&label_style, &animation_template);

  ui_Screen1_Amount_Value_Label = lv_label_create(ui_Panel1);  // 단위 표시
  lv_label_set_long_mode(ui_Screen1_Amount_Value_Label, LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_obj_set_width(ui_Screen1_Amount_Value_Label, 100);  /// 1
  lv_obj_set_height(ui_Screen1_Amount_Value_Label, 50);  /// 1
  lv_obj_set_x(ui_Screen1_Amount_Value_Label, 0);
  lv_obj_set_y(ui_Screen1_Amount_Value_Label, 28);
  lv_obj_set_align(ui_Screen1_Amount_Value_Label, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_recolor(ui_Screen1_Amount_Value_Label, true);
  lv_label_set_text(ui_Screen1_Amount_Value_Label, "#0000ff Max:100kg# #ff0000 Min:100g#");
  lv_obj_set_style_text_font(ui_Screen1_Amount_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_style(ui_Screen1_Amount_Value_Label, &label_style, LV_STATE_DEFAULT); /*Add the style to the label*/
  lv_obj_add_event_cb(ui_Screen1_Amount_Value_Label, ui_Screen1_Amount_Value_Label_e_handler, LV_EVENT_ALL, NULL);
  /* added animation */

  /*Screen1 button */

  ui_Screen1_Setting_Btn = lv_btn_create(ui_Screen1);  // setting button
  lv_obj_set_width(ui_Screen1_Setting_Btn, 100);
  lv_obj_set_height(ui_Screen1_Setting_Btn, 50);
  lv_obj_set_x(ui_Screen1_Setting_Btn, 160);
  lv_obj_set_y(ui_Screen1_Setting_Btn, -120);
  lv_obj_set_align(ui_Screen1_Setting_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Screen1_Setting_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Setting_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Setting_Btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Setting_Btn, ui_Screen1_Setting_Btn_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Setting_Btn_Label = lv_label_create(ui_Screen1_Setting_Btn);
  lv_obj_set_width(ui_Screen1_Setting_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Setting_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Setting_Btn_Label, 15);
  lv_obj_set_y(ui_Screen1_Setting_Btn_Label, 2);
  lv_label_set_text(ui_Screen1_Setting_Btn_Label, "설 정");
  lv_obj_set_style_text_font(ui_Screen1_Setting_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Prod_Num_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Prod_Num_Btn, 100);
  lv_obj_set_height(ui_Screen1_Prod_Num_Btn, 50);
  lv_obj_set_x(ui_Screen1_Prod_Num_Btn, 50);
  lv_obj_set_y(ui_Screen1_Prod_Num_Btn, -120);
  lv_obj_set_align(ui_Screen1_Prod_Num_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Screen1_Prod_Num_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Prod_Num_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Prod_Num_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Prod_Num_Btn, ui_event_Screen1_List_Select_Button, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_List_Select_Btn_Label = lv_label_create(ui_Screen1_Prod_Num_Btn);
  lv_obj_set_width(ui_Screen1_List_Select_Btn_Label, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_Screen1_List_Select_Btn_Label, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_Screen1_List_Select_Btn_Label, 15);
  lv_obj_set_y(ui_Screen1_List_Select_Btn_Label, 2);
  lv_label_set_text(ui_Screen1_List_Select_Btn_Label, "품 번");
  lv_obj_set_style_text_font(ui_Screen1_List_Select_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

#if CONFIG_ZERO_TARE_SET
  lv_obj_t *ui_Screen1_Zero_Point_Set_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Zero_Point_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Zero_Point_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Zero_Point_Set_Btn, -180);
  lv_obj_set_y(ui_Screen1_Zero_Point_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Zero_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Zero_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Zero_Point_Set_Btn, ui_Screen1_Zero_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Zero_Point_Set_Btn_Label = lv_label_create(ui_Screen1_Zero_Point_Set_Btn);
  lv_obj_set_width(ui_Screen1_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Zero_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Zero_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Zero_Point_Set_Btn_Label, "영점");
  lv_obj_set_style_text_font(ui_Screen1_Zero_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Tare_Point_Set_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Tare_Point_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Tare_Point_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Tare_Point_Set_Btn, -120);
  lv_obj_set_y(ui_Screen1_Tare_Point_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Tare_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Tare_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Tare_Point_Set_Btn, ui_Screen1_Tare_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Tare_Point_Set_Btn_Label = lv_label_create(ui_Screen1_Tare_Point_Set_Btn);
  lv_obj_set_width(ui_Screen1_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Tare_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Tare_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Tare_Point_Set_Btn_Label, "용기");
  lv_obj_set_style_text_font(ui_Screen1_Tare_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
#endif
  lv_obj_t *ui_Screen1_Mode_Set_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Mode_Set_Btn, 60);
  lv_obj_set_height(ui_Screen1_Mode_Set_Btn, 60);
  lv_obj_set_x(ui_Screen1_Mode_Set_Btn, 190);
  lv_obj_set_y(ui_Screen1_Mode_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Mode_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Mode_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Mode_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Mode_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Mode_Set_Btn, ui_Screen1_Mode_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Mode_Set_Btn_Label = lv_label_create(ui_Screen1_Mode_Set_Btn);
  lv_obj_set_width(ui_Screen1_Mode_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Mode_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Mode_Set_Btn_Label, 0);
  lv_obj_set_y(ui_Screen1_Mode_Set_Btn_Label, 10);
  lv_label_set_text(ui_Screen1_Mode_Set_Btn_Label, "모드");
  lv_obj_set_style_text_font(ui_Screen1_Mode_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  // lv_obj_t *ui_Screen1_Amount_Set_Btn = lv_btn_create(ui_Screen1);
  // lv_obj_set_width(ui_Screen1_Amount_Set_Btn, 50);
  // lv_obj_set_height(ui_Screen1_Amount_Set_Btn, 50);
  // lv_obj_set_x(ui_Screen1_Amount_Set_Btn, 120);
  // lv_obj_set_y(ui_Screen1_Amount_Set_Btn, -10);
  // lv_obj_set_align(ui_Screen1_Amount_Set_Btn, LV_ALIGN_BOTTOM_MID);
  // lv_obj_add_flag(ui_Screen1_Amount_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  // lv_obj_clear_flag(ui_Screen1_Amount_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  // lv_obj_set_style_bg_color(ui_Screen1_Amount_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  // lv_obj_add_event_cb(ui_Screen1_Amount_Set_Btn, ui_Screen1_Amount_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  // lv_obj_t *ui_Screen1_Amount_Set_Btn_Label = lv_label_create(ui_Screen1_Amount_Set_Btn);
  // lv_obj_set_width(ui_Screen1_Amount_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  // lv_obj_set_height(ui_Screen1_Amount_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  // lv_obj_set_x(ui_Screen1_Amount_Set_Btn_Label, -5);
  // lv_obj_set_y(ui_Screen1_Amount_Set_Btn_Label, 5);
  // lv_label_set_text(ui_Screen1_Amount_Set_Btn_Label, "단위");
  // lv_obj_set_style_text_font(ui_Screen1_Amount_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Judge_Comfirm_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Judge_Comfirm_Btn, 60);
  lv_obj_set_height(ui_Screen1_Judge_Comfirm_Btn, 60);
  lv_obj_set_x(ui_Screen1_Judge_Comfirm_Btn, 120);
  lv_obj_set_y(ui_Screen1_Judge_Comfirm_Btn, -10);
  lv_obj_set_align(ui_Screen1_Judge_Comfirm_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Judge_Comfirm_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Judge_Comfirm_Btn, ui_Screen1_Judge_Comfirm_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Judge_Comfirm_Btn_Label = lv_label_create(ui_Screen1_Judge_Comfirm_Btn);
  lv_obj_set_width(ui_Screen1_Judge_Comfirm_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Judge_Comfirm_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Judge_Comfirm_Btn_Label, 0);
  lv_obj_set_y(ui_Screen1_Judge_Comfirm_Btn_Label, 10);
  lv_label_set_text(ui_Screen1_Judge_Comfirm_Btn_Label, "완료");
  lv_obj_set_style_text_font(ui_Screen1_Judge_Comfirm_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Judge_Cancel_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Judge_Cancel_Btn, 60);
  lv_obj_set_height(ui_Screen1_Judge_Cancel_Btn, 60);
  lv_obj_set_x(ui_Screen1_Judge_Cancel_Btn, 50);
  lv_obj_set_y(ui_Screen1_Judge_Cancel_Btn, -10);
  lv_obj_set_align(ui_Screen1_Judge_Cancel_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Judge_Cancel_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Judge_Cancel_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Judge_Cancel_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Judge_Cancel_Btn, ui_Screen1_Judge_Cancel_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Judge_Cancel_Btn_Label = lv_label_create(ui_Screen1_Judge_Cancel_Btn);
  lv_obj_set_width(ui_Screen1_Judge_Cancel_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Judge_Cancel_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Judge_Cancel_Btn_Label, 0);
  lv_obj_set_y(ui_Screen1_Judge_Cancel_Btn_Label, 10);
  lv_label_set_text(ui_Screen1_Judge_Cancel_Btn_Label, "취소");
  lv_obj_set_style_text_font(ui_Screen1_Judge_Cancel_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Recently_Cancel_Btn = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_Screen1_Recently_Cancel_Btn, 60);
  lv_obj_set_height(ui_Screen1_Recently_Cancel_Btn, 60);
  lv_obj_set_x(ui_Screen1_Recently_Cancel_Btn, -20);
  lv_obj_set_y(ui_Screen1_Recently_Cancel_Btn, -10);
  lv_obj_set_align(ui_Screen1_Recently_Cancel_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Recently_Cancel_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Recently_Cancel_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Recently_Cancel_Btn, lv_color_hex(0x0E04F8), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Recently_Cancel_Btn, ui_Screen1_Recently_Cancel_Btn_e_handler, LV_EVENT_CLICKED, NULL);

  lv_obj_t *ui_Screen1_Recently_Cancel_Btn_Label = lv_label_create(ui_Screen1_Recently_Cancel_Btn);
  lv_obj_set_width(ui_Screen1_Recently_Cancel_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Recently_Cancel_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Recently_Cancel_Btn_Label, 0);
  lv_obj_set_y(ui_Screen1_Recently_Cancel_Btn_Label, 10);
  lv_label_set_text(ui_Screen1_Recently_Cancel_Btn_Label, " C");
  lv_obj_set_style_text_font(ui_Screen1_Recently_Cancel_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
}
