// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"
#include "log.h"
#include <stdio.h>
#include <math.h>
#include <ctype.h>
#include <stdbool.h>
#include "scale_read_485.h"

#define MAX_CHAR_CYCLES 5
static const char *TAG = "ui_mode_1_main_set_reg_Screen";

extern custom_msg_box_t *user_data_obj;
extern void Msg_Box_No_Btn_e_handler(lv_event_t *e);
extern void memory_allocation_manger();
extern void create_custom_msg_box(const char *msg_text, lv_obj_t *active_screen, void (*event_handler)(lv_event_t *),
                                  lv_event_code_t event);

typedef enum {
  FOCUS_TA_NONE = -1,
  FOCUS_TA1,
  FOCUS_TA2,
  FOCUS_TA3,
  FOCUS_TA4,
} focus_ta_t;

static bool ta1_selected = false;
static bool ta2_selected = false;
static bool ta3_selected = false;
static bool ta4_selected = false;
// static bool ta5_selected;

static textareas_t use_text_area;

int button_state[12] = { 0 };
focus_ta_t current_focus = FOCUS_TA1;
focus_ta_t previous_focus = FOCUS_TA_NONE;
int current_id = 0;
int previous_id = 0;

static const char *button_texts[12][MAX_CHAR_CYCLES] = {
  { "1", "1", "!", "@", "#" },  // ID 0
  { "2", "2", "A", "B", "C" },  // ID 1
  { "3", "3", "D", "E", "F" },  // ID 2
  { "4", "4", "G", "H", "I" },  // ID 3
  { "5", "5", "J", "K", "L" },  // ID 4
  { "6", "6", "M", "N", "O" },  // ID 5
  { "S", "7", "P", "Q", "R" },  // ID 6
  { "8", "8", "T", "U", "V" },  // ID 7
  { "Z", "9", "W", "X", "Y" },  // ID 8
  { " ", " ", " ", " ", " " },  // ID 9
  { "0", "0", ".", "-", "/" },  // ID 10
  { " ", " ", " ", " ", " " }   // ID 11 //공백으로 자리 확보
};

static const char *button_nums[12][2] = {
  { "1", "1" },  // ID 0
  { "2", "2" },  // ID 1
  { "3", "3" },  // ID 2
  { "4", "4" },  // ID 3
  { "5", "5" },  // ID 4
  { "6", "6" },  // ID 5
  { "7", "7" },  // ID 6
  { "8", "8" },  // ID 7
  { "9", "9" },  // ID 8
  { " ", " " },  // ID 9
  { ".", "0" },  // ID 10 // 0 first, . second
  { " ", " " }   // ID 11
};

static char *count_buf[] = { "kg", " g" };
static char **count_ptr = count_buf;
static weight_unit_t prod_unit = UNIT_KG;

void ui_prod_unit_set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target_label = lv_event_get_user_data(e);

  if (code == LV_EVENT_CLICKED) {
    count_ptr++;
    if (count_ptr >= count_buf + sizeof(count_buf) / sizeof(count_buf[0])) {
      count_ptr = count_buf;
    }
    lv_label_set_text(target_label, *count_ptr);
    if (strcmp(*count_ptr, "kg") == 0)
      prod_unit = UNIT_KG;
    if (strcmp(*count_ptr, " g") == 0)
      prod_unit = UNIT_G;
    LOGI(TAG, "prod unit :%s_%d", *count_ptr, prod_unit);
  }
}

void ui_all_delete_btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  textareas_t *ta = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED) {
    lv_textarea_set_text(ta->ta1, "\0");
    lv_textarea_set_text(ta->ta2, "\0");
    lv_textarea_set_text(ta->ta3, "\0");
    lv_textarea_set_text(ta->ta4, "\0");
  }
}

void ui_comfirm_btn_e_hendler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  textareas_t *ta = lv_event_get_user_data(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    lv_event_send(ta->ta1, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta2, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta3, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta4, LV_EVENT_READY, NULL);
    // lv_obj_clean(ui_Screen2);
  }
}

void textarea_event_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *ta = lv_event_get_target(e);

  if (code == LV_EVENT_FOCUSED) {
    ta1_selected = true;
    ta2_selected = false;
    ta3_selected = false;
    ta4_selected = false;
    // ta5_selected = false;
    LOGI(TAG, "event call ta1");
  } else if (code == LV_EVENT_READY) {
    // upper_weight_value = atoi(lv_textarea_get_text(ta));
    sscanf(lv_textarea_get_text(ta), "%f", &upper_weight_value);
    LOGI(TAG, "Enter was pressed. The current text is: %f", upper_weight_value);
  }
  /*Todo : */
}

void textarea_event_handler1(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *ta = lv_event_get_target(e);
  if (code == LV_EVENT_FOCUSED) {
    ta2_selected = true;
    ta1_selected = false;
    ta3_selected = false;
    ta4_selected = false;
    // ta5_selected = false;
    LOGI(TAG, "event call ta2");
  } else if (code == LV_EVENT_READY) {
    // lower_weight_value = atoi(lv_textarea_get_text(ta));
    sscanf(lv_textarea_get_text(ta), "%f", &lower_weight_value);
    LOGI(TAG, "Enter was pressed. The current text is: %f", lower_weight_value);
  }

  // /*Todo : */
}

void textarea_event_handler2(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *ta = lv_event_get_target(e);
  if (code == LV_EVENT_FOCUSED) {
    ta3_selected = true;
    ta1_selected = false;
    ta2_selected = false;
    ta4_selected = false;
    // ta5_selected = false;
    LOGI(TAG, "event call ta3");
  } else if (code == LV_EVENT_READY) {
    prod_num_value = atoi(lv_textarea_get_text(ta));
    LOGI(TAG, "Enter was pressed. The current text is: %d", prod_num_value);
  }
  // /*Todo : */
}

void textarea_event_handler3(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *ta = lv_event_get_target(e);
  if (code == LV_EVENT_FOCUSED) {
    ta4_selected = true;
    ta1_selected = false;
    ta2_selected = false;
    ta3_selected = false;

    // ta5_selected = false;
    LOGI(TAG, "event call ta4");
  } else if (code == LV_EVENT_READY) {
    memset(buf_prod_name, 0x00, sizeof(buf_prod_name));
    memcpy(buf_prod_name, lv_textarea_get_text(ta), strlen(lv_textarea_get_text(ta)));
    LOGI(TAG, "Enter was pressed. The current text is: %s", buf_prod_name);
  }
  // /*Todo : */
}

void btnm_event_handler(lv_event_t *e) {
  lv_obj_t *obj = lv_event_get_target(e);
  uint32_t id = lv_btnmatrix_get_selected_btn(obj);
  const char *txt = NULL;
  bool text_write_flag = false;
  LOGI(TAG, "btn_id %d", id);
  current_id = id;
  if (current_id != previous_id) {
    previous_id = current_id;
    memset(button_state, 0x00, sizeof(button_state));
  }

  // insert charicter initialize the current cursor position
  lv_obj_t *ta = use_text_area.ta1;

  if (ta1_selected) {
    ta = use_text_area.ta1;
    current_focus = FOCUS_TA1;
    if (current_focus != previous_focus) {
      memset(button_state, 0x00, sizeof(button_state));
      previous_focus = current_focus;
    }
    LOGI(TAG, "Send data to ta1");
  } else if (ta2_selected) {
    ta = use_text_area.ta2;
    current_focus = FOCUS_TA2;
    if (current_focus != previous_focus) {
      memset(button_state, 0x00, sizeof(button_state));
      previous_focus = current_focus;
    }

    LOGI(TAG, "Send data to ta2");
  } else if (ta3_selected) {
    ta = use_text_area.ta3;
    current_focus = FOCUS_TA3;
    if (current_focus != previous_focus) {
      memset(button_state, 0x00, sizeof(button_state));
      previous_focus = current_focus;
    }
    LOGI(TAG, "Send data to ta3");
  } else if (ta4_selected) {
    ta = use_text_area.ta4;
    current_focus = FOCUS_TA4;
    if (current_focus != previous_focus) {
      memset(button_state, 0x00, sizeof(button_state));
      previous_focus = current_focus;
    }
    LOGI(TAG, "Send data to ta4");
  } else {
    ta = use_text_area.ta1;
    current_focus = FOCUS_TA1;
    if (current_focus != previous_focus) {
      memset(button_state, 0x00, sizeof(button_state));
      previous_focus = current_focus;
    }
    LOGI(TAG, "Send data to ta1");
  }
  // 입력 문자 버퍼 초기
  if (id == 11) {
    memset(button_state, 0x00, sizeof(button_state));
  }

  if (ta == use_text_area.ta1 || ta == use_text_area.ta2 || ta == use_text_area.ta3) {
    if (id < 12) {
      button_state[id] = (button_state[id] + 1) % 2;
      if (id == 9) {
        txt = lv_btnmatrix_get_btn_text(obj, id);
        text_write_flag = false;
      } else {
        txt = button_nums[id][button_state[id]];
        text_write_flag = true;
      }
    }
  } else {
    if (id < 12) {
      button_state[id] = (button_state[id] + 1) % MAX_CHAR_CYCLES;
      if (id == 9) {
        txt = lv_btnmatrix_get_btn_text(obj, id);
        text_write_flag = false;
      } else {
        txt = button_texts[id][button_state[id]];
        text_write_flag = true;
      }
    }
  }

  // 같은자리 지우고 다시 쓰기 및 del 키 입력 시 문자삭제 및 자리이동
  if (id != 11) {
    if (id == 9 && strcmp(txt, "Del") == 0) {
      lv_textarea_cursor_left(ta);
      lv_textarea_del_char_forward(ta);
    } else
      lv_textarea_del_char(ta);
  }
  if (text_write_flag) {
    lv_textarea_add_text(ta, txt);
  }
}

static void event_cb(lv_event_t *e) {
  lv_obj_t *obj = lv_event_get_current_target(e);
  LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
  if (strcmp(lv_msgbox_get_active_btn_text(obj), "Close") == 0) {
    lv_msgbox_close(obj);
  }
}

static bool is_buffer_empty_or_whitespace(const char *buffer, size_t size) {
  for (size_t i = 0; i < size; ++i) {
    if (!isspace((unsigned char)buffer[i])) {
      return false;
    }
  }
  return true;
}

void register_set_parameter() {
  LOGI(TAG, "Register settings.");
  char set_str[50] = { 0 };
  char set_str_prodName[50] = { 0 };
  char s_key[10] = { 0 };
  char s_key_prodName[50] = { 0 };

  unsigned int upper_int_part = (int)upper_weight_value;
  unsigned int lower_int_part = (int)lower_weight_value;
  float upper_decimal_part = upper_weight_value - upper_int_part;
  float lower_decimal_part = lower_weight_value - lower_int_part;
  unsigned int upper_dacimal_to_int_part = roundf(upper_decimal_part * 1000);  // decimal point 3
  unsigned int lower_decimal_to_int_part = roundf(lower_decimal_part * 1000);  // rounding to the nearest integer

  snprintf(s_key, sizeof(s_key), "Prod%02d", prod_num_value);
  LOGI(TAG, "key:%s", s_key);

  if (prod_unit == UNIT_KG) {
    LOGI(TAG, "SET UNIT KG");
    upper_dacimal_to_int_part = roundf(upper_decimal_part * 1000);  // decimal point 3
    lower_decimal_to_int_part = roundf(lower_decimal_part * 1000);  // rounding to the nearest integer
    memset(set_str, 0x00, sizeof(set_str));
    snprintf(set_str, sizeof(set_str), "%02d,upper:%02d.%03d,lower:%02d.%03d,%d", prod_num_value, upper_int_part,
             upper_dacimal_to_int_part, lower_int_part, lower_decimal_to_int_part, prod_unit);
  } else if (prod_unit == UNIT_G) {
    LOGI(TAG, "SET UNIT G");
    upper_dacimal_to_int_part = roundf(upper_decimal_part * 10);  // decimal point 1
    lower_decimal_to_int_part = roundf(lower_decimal_part * 10);  // rounding to the nearest integer
    memset(set_str, 0x00, sizeof(set_str));
    snprintf(set_str, sizeof(set_str), "%02d,upper:%04d.%01d,lower:%04d.%01d,%d", prod_num_value, upper_int_part,
             upper_dacimal_to_int_part, lower_int_part, lower_decimal_to_int_part, prod_unit);
  }

  LOGI(TAG, "Set syscfg_data for setting value : %s", set_str);

  memset(set_str_prodName, 0x00, sizeof(set_str_prodName));
  snprintf(set_str_prodName, sizeof(set_str_prodName), "%s", buf_prod_name);
  LOGI(TAG, "Set syscfg_data for prodName : %s", set_str_prodName);
  snprintf(s_key_prodName, sizeof(s_key_prodName), "%s_%02d", PROD_NAME, prod_num_value);
  LOGI(TAG, "Set syscfg_data for s_key_prodName : %s", s_key_prodName);

  if (syscfg_set(CFG_DATA, s_key, set_str) == -1) {
    LOGI(TAG, "Error set register ");
  }
  if (syscfg_set(CFG_DATA, s_key_prodName, buf_prod_name) == -1) {
    LOGI(TAG, "Error set register prod name ");
  }
  return;
}

static void modify_register_Btn_Yes_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  // LOGI(TAG, "click Judge_Cancel_Btn_Yes_event_cb!!");
  if (code == LV_EVENT_CLICKED) {
    register_set_parameter();
    create_custom_msg_box("재등록 되었습니다. ", ui_Screen2, NULL, LV_EVENT_CLICKED);
  } else {
    memory_allocation_manger();
  }
}

void none_prod_name_set(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  if (code == LV_EVENT_CLICKED) {
    strcpy(buf_prod_name, "N/A");
    LOGI(TAG, "buf_prod_name : %s", buf_prod_name);
    register_set_parameter();
    create_custom_msg_box("품명없이 등록 되었습니다. ", ui_Screen2, NULL, LV_EVENT_CLICKED);
  } else {
    memory_allocation_manger();
  }
}

void ui_register_pord_num_btn_e_hendler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  textareas_t *ta = lv_event_get_user_data(e);

  char set_str[50] = { 0 };
  char set_str_prodName[50] = { 0 };
  char get_str[50] = { 0 };
  char s_key[10] = { 0 };
  char s_key_prodName[50] = { 0 };
  char cmp_pord_num[10] = { 0 };
  char cfg_pord_num[10] = { 0 };

  if (code == LV_EVENT_CLICKED) {
    lv_event_send(ta->ta1, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta2, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta3, LV_EVENT_READY, NULL);
    lv_event_send(ta->ta4, LV_EVENT_READY, NULL);

    /*start num 0, and Make sure enter it starts from number 0.*/
    memset(get_str, 0x00, sizeof(get_str));
    snprintf(s_key, sizeof(s_key), "Prod%02d", prod_num_value);
    LOGI(TAG, "key:%s", s_key);
    syscfg_get(CFG_DATA, s_key, get_str, sizeof(get_str));
    LOGI(TAG, "value:%s", get_str);
    /*compare same product num*/ /*"prodName" does not compare */
    snprintf(cmp_pord_num, sizeof(cmp_pord_num), "%02d", prod_num_value);
    snprintf(cfg_pord_num, sizeof(cfg_pord_num), "%.2s", get_str);

    if (upper_weight_value > (float)100 && prod_unit == UNIT_KG) {
      // erroe when entering product number over PROD_NUM value
      create_custom_msg_box("최대 상한값은 99.999kg 입니다.", ui_Screen2, NULL, LV_EVENT_CLICKED);

    } else if (upper_weight_value > (float)10000 && prod_unit == UNIT_G) {
      // erroe when entering product number over PROD_NUM value
      create_custom_msg_box("최대 상한값은 9999.9g 입니다.", ui_Screen2, NULL, LV_EVENT_CLICKED);

    } else if (prod_num_value > PROD_NUM) {
      // erroe when entering product number over PROD_NUM value
      create_custom_msg_box("등록 가능한 번호는 \n 0 ~ 30번 입니다.", ui_Screen2, NULL, LV_EVENT_CLICKED);

    } else if (lower_weight_value >= upper_weight_value && prod_num_value != 0) {
      // pord_num 0 is a special method that does not determine whether it works or not.
      create_custom_msg_box("유효하지 않은 설정 값입니다.\n부족값이 초과값과 같거나 클 수\n없습니다.", ui_Screen2, NULL,
                            LV_EVENT_CLICKED);
    } else if (buf_prod_name[0] == '\0') {
      // pord_name is a special method that does not determine whether it works or not.
      create_custom_msg_box("유효하지 않은 설정 값입니다.\n품명 없이 등록하겠습니까?", ui_Screen2, none_prod_name_set,
                            LV_EVENT_CLICKED);
    } else if (strcmp(cfg_pord_num, cmp_pord_num) == 0) {
      create_custom_msg_box("이미 등록된 번호가 있습니다\n변경하겠습니까?", ui_Screen2,
                            modify_register_Btn_Yes_e_handler, LV_EVENT_CLICKED);
    } else {
      if (strlen(get_str) == 0) {
        LOGI(TAG, "Register settings.");
        unsigned int upper_dacimal_to_int_part = 0;
        unsigned int lower_decimal_to_int_part = 0;

        unsigned int upper_int_part = (int)upper_weight_value;
        unsigned int lower_int_part = (int)lower_weight_value;
        float upper_decimal_part = upper_weight_value - upper_int_part;
        float lower_decimal_part = lower_weight_value - lower_int_part;

        if (prod_unit == UNIT_KG) {
          LOGI(TAG, "SET UNIT KG");
          upper_dacimal_to_int_part = roundf(upper_decimal_part * 1000);  // decimal point 3
          lower_decimal_to_int_part = roundf(lower_decimal_part * 1000);  // rounding to the nearest integer
          memset(set_str, 0x00, sizeof(set_str));
          snprintf(set_str, sizeof(set_str), "%02d,upper:%02d.%03d,lower:%02d.%03d,%d", prod_num_value, upper_int_part,
                   upper_dacimal_to_int_part, lower_int_part, lower_decimal_to_int_part, prod_unit);
        } else if (prod_unit == UNIT_G) {
          LOGI(TAG, "SET UNIT G");
          upper_dacimal_to_int_part = roundf(upper_decimal_part * 10);  // decimal point 1
          lower_decimal_to_int_part = roundf(lower_decimal_part * 10);  // rounding to the nearest integer
          memset(set_str, 0x00, sizeof(set_str));
          snprintf(set_str, sizeof(set_str), "%02d,upper:%04d.%01d,lower:%04d.%01d,%d", prod_num_value, upper_int_part,
                   upper_dacimal_to_int_part, lower_int_part, lower_decimal_to_int_part, prod_unit);
        }

        LOGI(TAG, "Set syscfg_data for setting value : %s", set_str);

        memset(set_str_prodName, 0x00, sizeof(set_str_prodName));
        snprintf(set_str_prodName, sizeof(set_str_prodName), "%s", buf_prod_name);
        LOGI(TAG, "Set syscfg_data for prodName : %s", set_str_prodName);
        snprintf(s_key_prodName, sizeof(s_key_prodName), "%s_%02d", PROD_NAME, prod_num_value);
        LOGI(TAG, "Set syscfg_data for s_key_prodName : %s", s_key_prodName);

        syscfg_set(CFG_DATA, s_key, set_str);
        syscfg_set(CFG_DATA, s_key_prodName, buf_prod_name);

        create_custom_msg_box("등록 되었습니다. ", ui_Screen2, NULL, LV_EVENT_CLICKED);
      }
    }
  }
}

void ui_Screen2_screen_init(void) {
  ui_Screen2 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  lv_obj_t *ui_prod_num_register_btn = lv_btn_create(ui_Screen2);
  lv_obj_set_width(ui_prod_num_register_btn, 70);
  lv_obj_set_height(ui_prod_num_register_btn, 50);
  lv_obj_set_x(ui_prod_num_register_btn, -190);
  lv_obj_set_y(ui_prod_num_register_btn, 70);
  lv_obj_set_align(ui_prod_num_register_btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_prod_num_register_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_prod_num_register_btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_prod_num_register_btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_prod_num_register_btn, ui_register_pord_num_btn_e_hendler, LV_EVENT_ALL, &use_text_area);

  lv_obj_t *Screen2_prod_num_register_btn_label = lv_label_create(ui_prod_num_register_btn);
  lv_obj_set_width(Screen2_prod_num_register_btn_label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(Screen2_prod_num_register_btn_label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(Screen2_prod_num_register_btn_label, -3);
  lv_obj_set_y(Screen2_prod_num_register_btn_label, 1);
  lv_label_set_text(Screen2_prod_num_register_btn_label, "등 록");
  lv_obj_set_style_text_font(Screen2_prod_num_register_btn_label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_prod_unit_btn = lv_btn_create(ui_Screen2);
  lv_obj_set_width(ui_prod_unit_btn, 70);
  lv_obj_set_height(ui_prod_unit_btn, 50);
  lv_obj_set_x(ui_prod_unit_btn, -110);
  lv_obj_set_y(ui_prod_unit_btn, 70);
  lv_obj_set_align(ui_prod_unit_btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_prod_unit_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_prod_unit_btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_prod_unit_btn, lv_color_hex(0xa9a9a9), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_prod_unit_btn_label = lv_label_create(ui_prod_unit_btn);
  lv_obj_set_width(ui_prod_unit_btn_label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_prod_unit_btn_label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_prod_unit_btn_label, -3);
  lv_obj_set_y(ui_prod_unit_btn_label, 1);
  lv_label_set_text(ui_prod_unit_btn_label, "kg");
  lv_obj_set_style_text_font(ui_prod_unit_btn_label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_prod_unit_btn, ui_prod_unit_set_Btn_e_handler, LV_EVENT_CLICKED, ui_prod_unit_btn_label);

  lv_obj_t *ui_comfirm_btn = lv_btn_create(ui_Screen2);
  lv_obj_set_width(ui_comfirm_btn, 70);
  lv_obj_set_height(ui_comfirm_btn, 50);
  lv_obj_set_x(ui_comfirm_btn, -190);
  lv_obj_set_y(ui_comfirm_btn, 130);
  lv_obj_set_align(ui_comfirm_btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_comfirm_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_comfirm_btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_comfirm_btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_comfirm_btn, ui_comfirm_btn_e_hendler, LV_EVENT_ALL, &use_text_area);

  lv_obj_t *Label_2_1 = lv_label_create(ui_comfirm_btn);
  lv_obj_set_width(Label_2_1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(Label_2_1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(Label_2_1, -3);
  lv_obj_set_y(Label_2_1, 1);
  lv_label_set_text(Label_2_1, "완 료");
  lv_obj_set_style_text_font(Label_2_1, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Button_all_delete = lv_btn_create(ui_Screen2);
  lv_obj_set_width(ui_Button_all_delete, 70);
  lv_obj_set_height(ui_Button_all_delete, 50);
  lv_obj_set_x(ui_Button_all_delete, -110);
  lv_obj_set_y(ui_Button_all_delete, 130);
  lv_obj_set_align(ui_Button_all_delete, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Button_all_delete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Button_all_delete, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Button_all_delete, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Button_all_delete, ui_all_delete_btn_e_handler, LV_EVENT_ALL, &use_text_area);

  lv_obj_t *ui_Label_all_dalete = lv_label_create(ui_Button_all_delete);
  lv_obj_set_width(ui_Label_all_dalete, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label_all_dalete, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label_all_dalete, -3);
  lv_obj_set_y(ui_Label_all_dalete, 1);
  lv_label_set_text(ui_Label_all_dalete, "삭 제");
  lv_obj_set_style_text_font(ui_Label_all_dalete, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  use_text_area.ta1 = lv_textarea_create(ui_Screen2);
  lv_textarea_set_one_line(use_text_area.ta1, true);
  lv_obj_set_width(use_text_area.ta1, 125);          /// 1
  lv_obj_set_height(use_text_area.ta1, 40);          /// 1
  lv_textarea_set_max_length(use_text_area.ta1, 7);  // 자리수 제한 7자리
  lv_obj_align(use_text_area.ta1, LV_ALIGN_TOP_MID, -130, 10);
  // lv_obj_add_event_cb(use_text_area.ta1, only_numbers_handler, LV_EVENT_INSERT, NULL);
  lv_obj_add_event_cb(use_text_area.ta1, textarea_event_handler, LV_EVENT_READY, NULL);
  lv_obj_add_event_cb(use_text_area.ta1, textarea_event_handler, LV_EVENT_FOCUSED, NULL);
  lv_obj_add_state(use_text_area.ta1, LV_STATE_DEFAULT); /*To be sure the cursor is visible*/

  use_text_area.ta2 = lv_textarea_create(ui_Screen2);
  lv_textarea_set_one_line(use_text_area.ta2, true);
  lv_obj_set_width(use_text_area.ta2, 125);          /// 1
  lv_obj_set_height(use_text_area.ta2, 40);          /// 1
  lv_textarea_set_max_length(use_text_area.ta2, 7);  // 자리수 제한 7자리
  lv_obj_align(use_text_area.ta2, LV_ALIGN_TOP_MID, -130, 60);
  lv_obj_add_event_cb(use_text_area.ta2, textarea_event_handler1, LV_EVENT_READY, NULL);
  lv_obj_add_event_cb(use_text_area.ta2, textarea_event_handler1, LV_EVENT_FOCUSED, NULL);
  lv_obj_add_state(use_text_area.ta2, LV_STATE_DEFAULT); /*To be sure the cursor is visible*/

  use_text_area.ta3 = lv_textarea_create(ui_Screen2);  // 정상 text
  lv_textarea_set_one_line(use_text_area.ta3, true);
  lv_obj_set_width(use_text_area.ta3, 125);          /// 1
  lv_obj_set_height(use_text_area.ta3, 40);          /// 1
  lv_textarea_set_max_length(use_text_area.ta3, 7);  // 자리수 제한 7자리
  lv_obj_align(use_text_area.ta3, LV_ALIGN_TOP_MID, -130, 110);
  lv_obj_add_event_cb(use_text_area.ta3, textarea_event_handler2, LV_EVENT_READY, NULL);
  lv_obj_add_event_cb(use_text_area.ta3, textarea_event_handler2, LV_EVENT_FOCUSED, NULL);
  lv_obj_add_state(use_text_area.ta3, LV_STATE_DEFAULT); /*To be sure the cursor is visible*/

  use_text_area.ta4 = lv_textarea_create(ui_Screen2);  // 품명
  lv_textarea_set_one_line(use_text_area.ta4, true);
  lv_obj_set_width(use_text_area.ta4, 125);          /// 1
  lv_obj_set_height(use_text_area.ta4, 40);          /// 1
  lv_textarea_set_max_length(use_text_area.ta4, 7);  // 자리수 제한 7자리
  lv_obj_align(use_text_area.ta4, LV_ALIGN_TOP_MID, -130, 160);
  lv_obj_add_event_cb(use_text_area.ta4, textarea_event_handler3, LV_EVENT_READY, NULL);
  lv_obj_add_event_cb(use_text_area.ta4, textarea_event_handler3, LV_EVENT_FOCUSED, NULL);
  lv_obj_add_state(use_text_area.ta4, LV_STATE_DEFAULT); /*To be sure the cursor is visible*/

  static const char *btnm_map[] = { "1 !@#",  "2 ABC", "3 DEF",  "\n", "4 GHI", "5 JKL", "6 MNO", "\n",
                                    "7 PQRS", "8 TUV", "9 WXYZ", "\n", "Del",   "0 .-/", "SPC",   "" };

  lv_obj_t *btnm = lv_btnmatrix_create(ui_Screen2);
  lv_obj_set_size(btnm, 300, 320);
  lv_obj_align(btnm, LV_ALIGN_BOTTOM_RIGHT, 0, 0);
  lv_obj_set_style_text_font(btnm, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(btnm, btnm_event_handler, LV_EVENT_VALUE_CHANGED, NULL);
  lv_obj_clear_flag(btnm, LV_OBJ_FLAG_CLICK_FOCUSABLE); /*To keep the text area focused on button clicks*/
  lv_btnmatrix_set_map(btnm, btnm_map);

  lv_obj_t *ui_Label8 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label8, -215);
  lv_obj_set_y(ui_Label8, 20);
  lv_obj_set_align(ui_Label8, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_Label8, "초 과");
  lv_obj_set_style_text_font(ui_Label8, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label9 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label9, -215);
  lv_obj_set_y(ui_Label9, 70);
  lv_obj_set_align(ui_Label9, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_Label9, "부 족");
  lv_obj_set_style_text_font(ui_Label9, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label10 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label10, -215);
  lv_obj_set_y(ui_Label10, 120);
  lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_Label10, "품 번");
  lv_obj_set_style_text_font(ui_Label10, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label11 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label11, -215);
  lv_obj_set_y(ui_Label11, 170);
  lv_obj_set_align(ui_Label11, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_Label11, "품 명");
  lv_obj_set_style_text_font(ui_Label11, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
}
