// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"
#include "log.h"

static const char *TAG = "ui_mode_2_scr";
static char *count_buf[] = { "  1", " 10", " 20", " 50", "100", "200" };
static char **count_ptr = count_buf;

void ui_mode_2_scr_Amount_Count_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target_label = lv_event_get_user_data(e);
  if (code == LV_EVENT_CLICKED) {
    count_ptr++;
    if (count_ptr >= count_buf + sizeof(count_buf) / sizeof(count_buf[0])) {
      count_ptr = count_buf;
    }
    mode_2_compare_count = atoi(*count_ptr);
    lv_label_set_text(target_label, *count_ptr);
    LOGI(TAG, "mode 2 compare count : %d", mode_2_compare_count);
  }
}

void ui_mode_2_scr_Panel1_Amount_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "단위 %.3f", amount_weight_value);
    lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

void ui_mode_2_scr_Zero_Point_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  int ret = 0;
  if (code == LV_EVENT_CLICKED) {
    ret = cas_zero_command();
  }
}
void ui_mode_2_scr_Tare_Point_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  int ret = 0;
  if (code == LV_EVENT_CLICKED) {
    memset(s_tare_set_value, 0x00, sizeof(s_tare_set_value));
    ret = cas_tare_command(s_tare_set_value);
  }
}

void ui_mode_2_scr_Mode_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  if (code == LV_EVENT_CLICKED) {
    ui_data_ctx.curr_mode = MODE_MAIN;
    _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_main_screen_init);
  }
}

void ui_mode_2_scr_Amount_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (code == LV_EVENT_CLICKED) {
    // ui_event = AMOUNT_VAL_E;
    ui_data_ctx.obj = ui_mode_2_scr_Panel1_Amount_Value_Label;
    ui_data_ctx.ids = AMOUNT_VAL_E;
  }
}

void ui_mode_2_scr_Judge_Comfirm_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (code == LV_EVENT_CLICKED) {
    // ui_event = AMOUNT_VAL_E;
    *ui_data_ctx.ptr = 0;  // init.
    ui_data_ctx.ids = JUDGE_COMFIRM_E;
  }
}

void ui_mode_2_screen_init(void) {
  ui_mode_2_scr = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_mode_2_scr, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  /* Screen1 main panel*/
  ui_mode_2_scr_Panel1 = lv_obj_create(ui_mode_2_scr);
  lv_obj_set_width(ui_mode_2_scr_Panel1, 392);
  lv_obj_set_height(ui_mode_2_scr_Panel1, 173);
  lv_obj_set_align(ui_mode_2_scr_Panel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_mode_2_scr_Panel1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  lv_obj_t *ui_mode_2_scr_Title_Label = lv_label_create(ui_mode_2_scr);  // 단위 표시
  lv_obj_set_width(ui_mode_2_scr_Title_Label, LV_SIZE_CONTENT);          /// 1
  lv_obj_set_height(ui_mode_2_scr_Title_Label, LV_SIZE_CONTENT);         /// 1
  lv_obj_set_x(ui_mode_2_scr_Title_Label, 0);
  lv_obj_set_y(ui_mode_2_scr_Title_Label, 25);
  lv_obj_set_align(ui_mode_2_scr_Title_Label, LV_ALIGN_TOP_MID);
  lv_label_set_text(ui_mode_2_scr_Title_Label, "단위판정모드");
  lv_obj_set_style_text_font(ui_mode_2_scr_Title_Label, &NanumBar32, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Current_Weight_Label = lv_label_create(ui_mode_2_scr_Panel1);  // weight display
  lv_obj_set_width(ui_mode_2_scr_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Current_Weight_Label, 15);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Current_Weight_Label, 10);
  lv_label_set_text(ui_mode_2_scr_Panel1_Current_Weight_Label, "0000");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Current_Weight_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Current_Count_Label = lv_label_create(ui_mode_2_scr_Panel1);  // count display
  lv_obj_set_width(ui_mode_2_scr_Panel1_Current_Count_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Current_Count_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Current_Count_Label, 240);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Current_Count_Label, 10);
  lv_label_set_text(ui_mode_2_scr_Panel1_Current_Count_Label, "000");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Current_Count_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Zero_Point_Label = lv_label_create(ui_mode_2_scr_Panel1);  // zero display
  lv_obj_set_width(ui_mode_2_scr_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Zero_Point_Label, 5);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Zero_Point_Label, 0);
  lv_obj_set_align(ui_mode_2_scr_Panel1_Zero_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_mode_2_scr_Panel1_Zero_Point_Label, "영점");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Zero_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Zero_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_mode_2_scr_Panel1_Zero_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Stable_Point_Label = lv_label_create(ui_mode_2_scr_Panel1);  // // stable display
  lv_obj_set_width(ui_mode_2_scr_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Stable_Point_Label, 50);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Stable_Point_Label, 0);
  lv_obj_set_align(ui_mode_2_scr_Panel1_Stable_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_mode_2_scr_Panel1_Stable_Point_Label, "안정");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Stable_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Stable_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_mode_2_scr_Panel1_Stable_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Tare_Point_Label = lv_label_create(ui_mode_2_scr_Panel1);  // // stable display
  lv_obj_set_width(ui_mode_2_scr_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Tare_Point_Label, 95);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Tare_Point_Label, 0);
  lv_obj_set_align(ui_mode_2_scr_Panel1_Tare_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_mode_2_scr_Panel1_Tare_Point_Label, "용기");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Tare_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Tare_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_mode_2_scr_Panel1_Tare_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_mode_2_scr_Label_total_amount = lv_label_create(ui_mode_2_scr_Panel1);  // 총수량
  lv_obj_set_width(ui_mode_2_scr_Label_total_amount, LV_SIZE_CONTENT);                 /// 1
  lv_obj_set_height(ui_mode_2_scr_Label_total_amount, LV_SIZE_CONTENT);                /// 1
  lv_obj_set_x(ui_mode_2_scr_Label_total_amount, -30);
  lv_obj_set_y(ui_mode_2_scr_Label_total_amount, 0);
  lv_obj_set_align(ui_mode_2_scr_Label_total_amount, LV_ALIGN_TOP_RIGHT);
  lv_label_set_text(ui_mode_2_scr_Label_total_amount, "총수량");
  lv_obj_set_style_text_font(ui_mode_2_scr_Label_total_amount, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mode_2_scr_Panel1_Amount_Value_Label = lv_label_create(ui_mode_2_scr_Panel1);  // 단위 표시
  lv_obj_set_width(ui_mode_2_scr_Panel1_Amount_Value_Label, LV_SIZE_CONTENT);       /// 1
  lv_obj_set_height(ui_mode_2_scr_Panel1_Amount_Value_Label, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_x(ui_mode_2_scr_Panel1_Amount_Value_Label, 0);
  lv_obj_set_y(ui_mode_2_scr_Panel1_Amount_Value_Label, 5);
  lv_obj_set_align(ui_mode_2_scr_Panel1_Amount_Value_Label, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_text(ui_mode_2_scr_Panel1_Amount_Value_Label, "단위");
  lv_obj_set_style_text_font(ui_mode_2_scr_Panel1_Amount_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_mode_2_scr_Panel1_Amount_Value_Label, ui_mode_2_scr_Panel1_Amount_Value_Label_e_handler,
                      LV_EVENT_ALL, NULL);

  /*Screen1 button */
#if CONFIG_ZERO_TARE_SET
  lv_obj_t *ui_mode_2_scr_Zero_Point_Set_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  lv_obj_set_width(ui_mode_2_scr_Zero_Point_Set_Btn, 50);
  lv_obj_set_height(ui_mode_2_scr_Zero_Point_Set_Btn, 50);
  lv_obj_set_x(ui_mode_2_scr_Zero_Point_Set_Btn, -180);
  lv_obj_set_y(ui_mode_2_scr_Zero_Point_Set_Btn, -10);
  lv_obj_set_align(ui_mode_2_scr_Zero_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_mode_2_scr_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mode_2_scr_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_mode_2_scr_Zero_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_mode_2_scr_Zero_Point_Set_Btn, ui_mode_2_scr_Zero_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_mode_2_scr_Zero_Point_Set_Btn_Label = lv_label_create(ui_mode_2_scr_Zero_Point_Set_Btn);
  lv_obj_set_width(ui_mode_2_scr_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_mode_2_scr_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mode_2_scr_Zero_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_mode_2_scr_Zero_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_mode_2_scr_Zero_Point_Set_Btn_Label, "영점");
  lv_obj_set_style_text_font(ui_mode_2_scr_Zero_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_mode_2_scr_Tare_Point_Set_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  lv_obj_set_width(ui_mode_2_scr_Tare_Point_Set_Btn, 50);
  lv_obj_set_height(ui_mode_2_scr_Tare_Point_Set_Btn, 50);
  lv_obj_set_x(ui_mode_2_scr_Tare_Point_Set_Btn, -120);
  lv_obj_set_y(ui_mode_2_scr_Tare_Point_Set_Btn, -10);
  lv_obj_set_align(ui_mode_2_scr_Tare_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_mode_2_scr_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mode_2_scr_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_mode_2_scr_Tare_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_mode_2_scr_Tare_Point_Set_Btn, ui_mode_2_scr_Tare_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_mode_2_scr_Tare_Point_Set_Btn_Label = lv_label_create(ui_mode_2_scr_Tare_Point_Set_Btn);
  lv_obj_set_width(ui_mode_2_scr_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_mode_2_scr_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mode_2_scr_Tare_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_mode_2_scr_Tare_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_mode_2_scr_Tare_Point_Set_Btn_Label, "용기");
  lv_obj_set_style_text_font(ui_mode_2_scr_Tare_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
#endif

  lv_obj_t *ui_mode_2_scr_Mode_Set_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  lv_obj_set_width(ui_mode_2_scr_Mode_Set_Btn, 60);
  lv_obj_set_height(ui_mode_2_scr_Mode_Set_Btn, 60);
  lv_obj_set_x(ui_mode_2_scr_Mode_Set_Btn, 190);
  lv_obj_set_y(ui_mode_2_scr_Mode_Set_Btn, -10);
  lv_obj_set_align(ui_mode_2_scr_Mode_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_mode_2_scr_Mode_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mode_2_scr_Mode_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_mode_2_scr_Mode_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_mode_2_scr_Mode_Set_Btn, ui_mode_2_scr_Mode_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_mode_2_scr_Mode_Set_Btn_Label = lv_label_create(ui_mode_2_scr_Mode_Set_Btn);
  lv_obj_set_width(ui_mode_2_scr_Mode_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_mode_2_scr_Mode_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mode_2_scr_Mode_Set_Btn_Label, -2);
  lv_obj_set_y(ui_mode_2_scr_Mode_Set_Btn_Label, 10);
  lv_label_set_text(ui_mode_2_scr_Mode_Set_Btn_Label, "모드");
  lv_obj_set_style_text_font(ui_mode_2_scr_Mode_Set_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_mode_2_scr_Amount_Set_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  lv_obj_set_width(ui_mode_2_scr_Amount_Set_Btn, 60);
  lv_obj_set_height(ui_mode_2_scr_Amount_Set_Btn, 60);
  lv_obj_set_x(ui_mode_2_scr_Amount_Set_Btn, 120);
  lv_obj_set_y(ui_mode_2_scr_Amount_Set_Btn, -10);
  lv_obj_set_align(ui_mode_2_scr_Amount_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_mode_2_scr_Amount_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mode_2_scr_Amount_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_mode_2_scr_Amount_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_mode_2_scr_Amount_Set_Btn, ui_mode_2_scr_Amount_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_mode_2_scr_Amount_Set_Btn_Label = lv_label_create(ui_mode_2_scr_Amount_Set_Btn);
  lv_obj_set_width(ui_mode_2_scr_Amount_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_mode_2_scr_Amount_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mode_2_scr_Amount_Set_Btn_Label, -2);
  lv_obj_set_y(ui_mode_2_scr_Amount_Set_Btn_Label, 10);
  lv_label_set_text(ui_mode_2_scr_Amount_Set_Btn_Label, "단위");
  lv_obj_set_style_text_font(ui_mode_2_scr_Amount_Set_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_mode_2_scr_Amount_Count_Set_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  lv_obj_set_width(ui_mode_2_scr_Amount_Count_Set_Btn, 60);
  lv_obj_set_height(ui_mode_2_scr_Amount_Count_Set_Btn, 60);
  lv_obj_set_x(ui_mode_2_scr_Amount_Count_Set_Btn, 50);
  lv_obj_set_y(ui_mode_2_scr_Amount_Count_Set_Btn, -10);
  lv_obj_set_align(ui_mode_2_scr_Amount_Count_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_mode_2_scr_Amount_Count_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mode_2_scr_Amount_Count_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_mode_2_scr_Amount_Count_Set_Btn, lv_color_hex(0x0E04F8),
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_mode_2_scr_Amount_Count_Set_Btn_Label = lv_label_create(ui_mode_2_scr_Amount_Count_Set_Btn);
  lv_obj_set_width(ui_mode_2_scr_Amount_Count_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_mode_2_scr_Amount_Count_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mode_2_scr_Amount_Count_Set_Btn_Label, 0);
  lv_obj_set_y(ui_mode_2_scr_Amount_Count_Set_Btn_Label, 10);
  lv_label_set_text(ui_mode_2_scr_Amount_Count_Set_Btn_Label, " 1");
  lv_obj_set_style_text_font(ui_mode_2_scr_Amount_Count_Set_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_mode_2_scr_Amount_Count_Set_Btn, ui_mode_2_scr_Amount_Count_Set_Btn_e_handler, LV_EVENT_ALL,
                      ui_mode_2_scr_Amount_Count_Set_Btn_Label);

  // lv_obj_t *ui_mode_2_scr_Judge_Comfirm_Btn = lv_btn_create(ui_mode_2_scr);  // zero set button
  // lv_obj_set_width(ui_mode_2_scr_Judge_Comfirm_Btn, 50);
  // lv_obj_set_height(ui_mode_2_scr_Judge_Comfirm_Btn, 50);
  // lv_obj_set_x(ui_mode_2_scr_Judge_Comfirm_Btn, 60);
  // lv_obj_set_y(ui_mode_2_scr_Judge_Comfirm_Btn, -10);
  // lv_obj_set_align(ui_mode_2_scr_Judge_Comfirm_Btn, LV_ALIGN_BOTTOM_MID);
  // lv_obj_add_flag(ui_mode_2_scr_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  // lv_obj_clear_flag(ui_mode_2_scr_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  // lv_obj_set_style_bg_color(ui_mode_2_scr_Judge_Comfirm_Btn, lv_color_hex(0xff0060), LV_PART_MAIN |
  // LV_STATE_DEFAULT);

  // lv_obj_add_event_cb(ui_mode_2_scr_Judge_Comfirm_Btn, ui_mode_2_scr_Judge_Comfirm_Btn_e_handler, LV_EVENT_ALL,
  // NULL);

  // lv_obj_t *ui_mode_2_scr_Judge_Comfirm_BtnLabel = lv_label_create(ui_mode_2_scr_Judge_Comfirm_Btn);
  // lv_obj_set_width(ui_mode_2_scr_Judge_Comfirm_BtnLabel, LV_SIZE_CONTENT);   /// 1
  // lv_obj_set_height(ui_mode_2_scr_Judge_Comfirm_BtnLabel, LV_SIZE_CONTENT);  /// 1
  // lv_obj_set_x(ui_mode_2_scr_Judge_Comfirm_BtnLabel, -5);
  // lv_obj_set_y(ui_mode_2_scr_Judge_Comfirm_BtnLabel, 5);
  // lv_label_set_text(ui_mode_2_scr_Judge_Comfirm_BtnLabel, "완료");
  // lv_obj_set_style_text_font(ui_mode_2_scr_Judge_Comfirm_BtnLabel, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
}
