// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_led1  = lv_led_create(ui_Screen1);
lv_obj_align(ui_led1, LV_ALIGN_TOP_LEFT, 20, 20);
lv_led_set_color(ui_led1, lv_palette_main(LV_PALETTE_LIGHT_GREEN));
lv_led_off(ui_led1);

/*Copy the previous LED and set a brightness*/
ui_led2  = lv_led_create(ui_Screen1);
lv_obj_align(ui_led2, LV_ALIGN_TOP_LEFT, 100, 20);
lv_led_set_brightness(ui_led2, 150);
lv_led_set_color(ui_led2, lv_palette_main(LV_PALETTE_RED));

/*Copy the previous LED and switch it ON*/
ui_led3  = lv_led_create(ui_Screen1);
lv_obj_align(ui_led3, LV_ALIGN_TOP_LEFT, 180, 20);
lv_led_on(ui_led3);

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 392);
lv_obj_set_height( ui_Panel4, 173);
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 30 );
lv_obj_set_y( ui_Label2, 10 );
lv_label_set_text(ui_Label2,"Product Num");
lv_obj_set_style_text_font(ui_Label2, &ui_font_Display90, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 240 );
lv_obj_set_y( ui_Label3, 10 );
lv_label_set_text(ui_Label3,"Product Num");
lv_obj_set_style_text_font(ui_Label3, &ui_font_Display90, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 137 );
lv_obj_set_y( ui_Button1, -120 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 10 );
lv_obj_set_y( ui_Label4, 0 );
lv_label_set_text(ui_Label4,"설 정");
lv_obj_set_style_text_font(ui_Label4, &NanumBar24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
