// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "../ui.h"
#include "log.h"

static const char *TAG = "  ui_Screen1";

void ui_Screen1_Prod_Num_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "품번 %02d", prod_num_value);
    lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

void ui_Screen1_Upper_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "상한 %.3f", upper_weight_value);
    lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

void ui_Screen1_Lower_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "하한 %.3f", lower_weight_value);
    lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

void ui_Screen1_Amount_Value_Label_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_buff[30] = { 0 };
  if (code == LV_EVENT_READY) {
    snprintf(s_buff, sizeof(s_buff), "단위 %.3f kg", amount_weight_value);
    lv_label_set_text(target, s_buff);
  }
  /*Todo : */
}

void ui_Screen1_Amount_Set_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (code == LV_EVENT_CLICKED) {
    // ui_event = AMOUNT_VAL_E;
    ui_data_ctx.obj = ui_Screen1_Amount_Value_Label;
    ui_data_ctx.ids = AMOUNT_VAL_E;
  }
}

void ui_Screen1_Judge_Comfirm_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (code == LV_EVENT_CLICKED) {
    // ui_event = AMOUNT_VAL_E;
    *ui_data_ctx.ptr = 0;  // init.
    ui_data_ctx.ids = JUDGE_COMFIRM_E;
  }
}

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  /* screen1 leds*/
  ui_led1 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led1, LV_ALIGN_TOP_LEFT, 30, 40);
  lv_led_set_color(ui_led1, lv_palette_main(LV_PALETTE_LIGHT_GREEN));
  lv_led_off(ui_led1);

  ui_led2 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led2, LV_ALIGN_TOP_LEFT, 95, 40);
  lv_led_set_brightness(ui_led2, 150);
  lv_led_set_color(ui_led2, lv_palette_main(LV_PALETTE_RED));

  ui_led3 = lv_led_create(ui_Screen1);
  lv_obj_align(ui_led3, LV_ALIGN_TOP_LEFT, 160, 40);
  lv_led_on(ui_led3);

  lv_obj_t *ui_Label5 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label5, 29);
  lv_obj_set_y(ui_Label5, 10);
  lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Label5, "초 과");
  lv_obj_set_style_text_font(ui_Label5, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label6 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label6, 96);
  lv_obj_set_y(ui_Label6, 10);
  lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Label6, "정 상");
  lv_obj_set_style_text_font(ui_Label6, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label7 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label7, 159);
  lv_obj_set_y(ui_Label7, 10);
  lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Label7, "부 족");
  lv_obj_set_style_text_font(ui_Label7, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  /* Screen1 main panel*/
  ui_Panel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel1, 392);
  lv_obj_set_height(ui_Panel1, 173);
  lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_Screen1_Panel1_Current_Weight_Label = lv_label_create(ui_Panel1);         // weight display
  lv_obj_set_width(ui_Screen1_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Current_Weight_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Current_Weight_Label, 15);
  lv_obj_set_y(ui_Screen1_Panel1_Current_Weight_Label, 10);
  lv_label_set_text(ui_Screen1_Panel1_Current_Weight_Label, "0000");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Current_Weight_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Current_Count_Label = lv_label_create(ui_Panel1);         // count display
  lv_obj_set_width(ui_Screen1_Panel1_Current_Count_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Current_Count_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Current_Count_Label, 240);
  lv_obj_set_y(ui_Screen1_Panel1_Current_Count_Label, 10);
  lv_label_set_text(ui_Screen1_Panel1_Current_Count_Label, "000");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Current_Count_Label, &ui_font_Display90,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Zero_Point_Label = lv_label_create(ui_Panel1);         // zero display
  lv_obj_set_width(ui_Screen1_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Zero_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Zero_Point_Label, 5);
  lv_obj_set_y(ui_Screen1_Panel1_Zero_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Zero_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Zero_Point_Label, "-Z-");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Zero_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Zero_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Zero_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Stable_Point_Label = lv_label_create(ui_Panel1);         // // stable display
  lv_obj_set_width(ui_Screen1_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Stable_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Stable_Point_Label, 50);
  lv_obj_set_y(ui_Screen1_Panel1_Stable_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Stable_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Stable_Point_Label, "-S-");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Stable_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Stable_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Stable_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Panel1_Tare_Point_Label = lv_label_create(ui_Panel1);         // // stable display
  lv_obj_set_width(ui_Screen1_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Panel1_Tare_Point_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Panel1_Tare_Point_Label, 95);
  lv_obj_set_y(ui_Screen1_Panel1_Tare_Point_Label, 0);
  lv_obj_set_align(ui_Screen1_Panel1_Tare_Point_Label, LV_ALIGN_TOP_LEFT);
  lv_label_set_text(ui_Screen1_Panel1_Tare_Point_Label, "-T-");
  lv_obj_set_style_text_font(ui_Screen1_Panel1_Tare_Point_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_Screen1_Panel1_Tare_Point_Label, lv_color_hex(0xe9e9e9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Screen1_Panel1_Tare_Point_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Label_total_amount = lv_label_create(ui_Panel1);  // 총수량
  lv_obj_set_width(ui_Label_total_amount, LV_SIZE_CONTENT);      /// 1
  lv_obj_set_height(ui_Label_total_amount, LV_SIZE_CONTENT);     /// 1
  lv_obj_set_x(ui_Label_total_amount, -30);
  lv_obj_set_y(ui_Label_total_amount, 0);
  lv_obj_set_align(ui_Label_total_amount, LV_ALIGN_TOP_RIGHT);
  lv_label_set_text(ui_Label_total_amount, "총수량");
  lv_obj_set_style_text_font(ui_Label_total_amount, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Screen1_Prod_Num_Label = lv_label_create(ui_Panel1);         // 총수량
  lv_obj_set_width(ui_Screen1_Prod_Num_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Prod_Num_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Prod_Num_Label, -150);
  lv_obj_set_y(ui_Screen1_Prod_Num_Label, 0);
  lv_obj_set_align(ui_Screen1_Prod_Num_Label, LV_ALIGN_TOP_RIGHT);
  lv_label_set_text(ui_Screen1_Prod_Num_Label, "품번");
  lv_obj_set_style_text_font(ui_Screen1_Prod_Num_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Prod_Num_Label, ui_Screen1_Prod_Num_Label_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Upper_Value_Label = lv_label_create(ui_Panel1);         // 상한값 표시
  lv_obj_set_width(ui_Screen1_Upper_Value_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Upper_Value_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Upper_Value_Label, 5);
  lv_obj_set_y(ui_Screen1_Upper_Value_Label, 5);
  lv_obj_set_align(ui_Screen1_Upper_Value_Label, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_Screen1_Upper_Value_Label, "상한");
  lv_obj_set_style_text_font(ui_Screen1_Upper_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Upper_Value_Label, ui_Screen1_Upper_Value_Label_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Lower_Value_Label = lv_label_create(ui_Panel1);         // 하한값 표시
  lv_obj_set_width(ui_Screen1_Lower_Value_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Lower_Value_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Lower_Value_Label, 115);
  lv_obj_set_y(ui_Screen1_Lower_Value_Label, 5);
  lv_obj_set_align(ui_Screen1_Lower_Value_Label, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_Screen1_Lower_Value_Label, "하한");
  lv_obj_set_style_text_font(ui_Screen1_Lower_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Lower_Value_Label, ui_Screen1_Lower_Value_Label_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Amount_Value_Label = lv_label_create(ui_Panel1);         // 단위 표시
  lv_obj_set_width(ui_Screen1_Amount_Value_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Amount_Value_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Amount_Value_Label, 0);
  lv_obj_set_y(ui_Screen1_Amount_Value_Label, 5);
  lv_obj_set_align(ui_Screen1_Amount_Value_Label, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_text(ui_Screen1_Amount_Value_Label, "단위");
  lv_obj_set_style_text_font(ui_Screen1_Amount_Value_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_event_cb(ui_Screen1_Amount_Value_Label, ui_Screen1_Amount_Value_Label_e_handler, LV_EVENT_ALL, NULL);

  /*Screen1 button */

  ui_Screen1_Setting_Btn = lv_btn_create(ui_Screen1);  // setting button
  lv_obj_set_width(ui_Screen1_Setting_Btn, 100);
  lv_obj_set_height(ui_Screen1_Setting_Btn, 50);
  lv_obj_set_x(ui_Screen1_Setting_Btn, 150);
  lv_obj_set_y(ui_Screen1_Setting_Btn, -120);
  lv_obj_set_align(ui_Screen1_Setting_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Screen1_Setting_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Setting_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Setting_Btn, lv_color_hex(0x0079ff), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Setting_Btn, ui_Screen1_Setting_Btn_e_handler, LV_EVENT_ALL, NULL);

  ui_Screen1_Setting_Btn_Label = lv_label_create(ui_Screen1_Setting_Btn);
  lv_obj_set_width(ui_Screen1_Setting_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Setting_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Setting_Btn_Label, 15);
  lv_obj_set_y(ui_Screen1_Setting_Btn_Label, 2);
  lv_label_set_text(ui_Screen1_Setting_Btn_Label, "설 정");
  lv_obj_set_style_text_font(ui_Screen1_Setting_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Prod_Num_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Prod_Num_Btn, 100);
  lv_obj_set_height(ui_Screen1_Prod_Num_Btn, 50);
  lv_obj_set_x(ui_Screen1_Prod_Num_Btn, 40);
  lv_obj_set_y(ui_Screen1_Prod_Num_Btn, -120);
  lv_obj_set_align(ui_Screen1_Prod_Num_Btn, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Screen1_Prod_Num_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Prod_Num_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Prod_Num_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Prod_Num_Btn, ui_event_Screen1_List_Select_Button, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_List_Select_Btn_Label = lv_label_create(ui_Screen1_Prod_Num_Btn);
  lv_obj_set_width(ui_Screen1_List_Select_Btn_Label, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_Screen1_List_Select_Btn_Label, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_Screen1_List_Select_Btn_Label, 15);
  lv_obj_set_y(ui_Screen1_List_Select_Btn_Label, 2);
  lv_label_set_text(ui_Screen1_List_Select_Btn_Label, "품 번");
  lv_obj_set_style_text_font(ui_Screen1_List_Select_Btn_Label, &NanumBar24, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Zero_Point_Set_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Zero_Point_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Zero_Point_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Zero_Point_Set_Btn, -180);
  lv_obj_set_y(ui_Screen1_Zero_Point_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Zero_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Zero_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Zero_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Zero_Point_Set_Btn, ui_Screen1_Zero_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Zero_Point_Set_Btn_Label = lv_label_create(ui_Screen1_Zero_Point_Set_Btn);
  lv_obj_set_width(ui_Screen1_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Zero_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Zero_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Zero_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Zero_Point_Set_Btn_Label, "영점");
  lv_obj_set_style_text_font(ui_Screen1_Zero_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Tare_Point_Set_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Tare_Point_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Tare_Point_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Tare_Point_Set_Btn, -120);
  lv_obj_set_y(ui_Screen1_Tare_Point_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Tare_Point_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Tare_Point_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Tare_Point_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Tare_Point_Set_Btn, ui_Screen1_Tare_Point_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Tare_Point_Set_Btn_Label = lv_label_create(ui_Screen1_Tare_Point_Set_Btn);
  lv_obj_set_width(ui_Screen1_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Tare_Point_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Tare_Point_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Tare_Point_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Tare_Point_Set_Btn_Label, "용기");
  lv_obj_set_style_text_font(ui_Screen1_Tare_Point_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Mode_Set_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Mode_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Mode_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Mode_Set_Btn, 180);
  lv_obj_set_y(ui_Screen1_Mode_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Mode_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Mode_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Mode_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Mode_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Mode_Set_Btn, ui_Screen1_Mode_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Mode_Set_Btn_Label = lv_label_create(ui_Screen1_Mode_Set_Btn);
  lv_obj_set_width(ui_Screen1_Mode_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Mode_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Mode_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Mode_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Mode_Set_Btn_Label, "모드");
  lv_obj_set_style_text_font(ui_Screen1_Mode_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Amount_Set_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Amount_Set_Btn, 50);
  lv_obj_set_height(ui_Screen1_Amount_Set_Btn, 50);
  lv_obj_set_x(ui_Screen1_Amount_Set_Btn, 120);
  lv_obj_set_y(ui_Screen1_Amount_Set_Btn, -10);
  lv_obj_set_align(ui_Screen1_Amount_Set_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Amount_Set_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Amount_Set_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Amount_Set_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Amount_Set_Btn, ui_Screen1_Amount_Set_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Amount_Set_Btn_Label = lv_label_create(ui_Screen1_Amount_Set_Btn);
  lv_obj_set_width(ui_Screen1_Amount_Set_Btn_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Amount_Set_Btn_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Amount_Set_Btn_Label, -5);
  lv_obj_set_y(ui_Screen1_Amount_Set_Btn_Label, 5);
  lv_label_set_text(ui_Screen1_Amount_Set_Btn_Label, "단위");
  lv_obj_set_style_text_font(ui_Screen1_Amount_Set_Btn_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *ui_Screen1_Judge_Comfirm_Btn = lv_btn_create(ui_Screen1);  // zero set button
  lv_obj_set_width(ui_Screen1_Judge_Comfirm_Btn, 50);
  lv_obj_set_height(ui_Screen1_Judge_Comfirm_Btn, 50);
  lv_obj_set_x(ui_Screen1_Judge_Comfirm_Btn, 60);
  lv_obj_set_y(ui_Screen1_Judge_Comfirm_Btn, -10);
  lv_obj_set_align(ui_Screen1_Judge_Comfirm_Btn, LV_ALIGN_BOTTOM_MID);
  lv_obj_add_flag(ui_Screen1_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Screen1_Judge_Comfirm_Btn, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_bg_color(ui_Screen1_Judge_Comfirm_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Screen1_Judge_Comfirm_Btn, ui_Screen1_Judge_Comfirm_Btn_e_handler, LV_EVENT_ALL, NULL);

  lv_obj_t *ui_Screen1_Judge_Comfirm_BtnLabel = lv_label_create(ui_Screen1_Judge_Comfirm_Btn);
  lv_obj_set_width(ui_Screen1_Judge_Comfirm_BtnLabel, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Screen1_Judge_Comfirm_BtnLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Screen1_Judge_Comfirm_BtnLabel, -5);
  lv_obj_set_y(ui_Screen1_Judge_Comfirm_BtnLabel, 5);
  lv_label_set_text(ui_Screen1_Judge_Comfirm_BtnLabel, "완료");
  lv_obj_set_style_text_font(ui_Screen1_Judge_Comfirm_BtnLabel, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
}
