#ifndef _EVENT_IDS_H_
#define _EVENT_IDS_H_

enum {
  I2C_TEMPERATURE_EVENT = 1,
  I2C_HUMIDITY_EVENT = 2,
  ADC_BATTERY_EVENT = 3,
  I2C_CO2_EVENT = 4,
  EASY_SETUP_DONE = 5,
  MDNS_EVENT = 6,
  MDNS_START = 7,
  MDNS_STOP = 8,
  NO_NETWORK_EVENT = 9,
  OK_NETWORK_EVENT = 10,
  NO_INTERNET_EVENT = 11,
  OK_INTERNET_EVENT = 12,
  HEAP_CRITICAL_LEVEL_WARNING_EVENT = 13,
  HEAP_WARNING_LEVEL_WARNING_EVENT = 14,
  TASK_MONITOR_EVENT = 15,
  ACTUATOR_AUTO = 16,
  ACTUATOR_PORT1 = 17,
  ACTUATOR_PORT2 = 18,
  ACTUATOR_PORT3 = 19,
  ACTUATOR_PORT4 = 20,
  ACTUATOR_PORT5 = 21,
  ACTUATOR_PORT6 = 22,
  ACTUATOR_PORT7 = 23,
  ACTUATOR_PORT8 = 24,
};

#define ACTUATOR_BASE 16

#endif /* _EVENT_IDS_H_ */
