// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#include "../ui.h"
#include "../ui_events.h"
#include "lv_conf_internal.h"

#define UI_LABEL_CREATE(lbl, parent, x_, y_, text_)                                             \
  do {                                                                                          \
    (lbl) = lv_label_create((parent));                                                          \
    lv_obj_set_size((lbl), LV_SIZE_CONTENT, LV_SIZE_CONTENT);                                   \
    lv_obj_set_pos((lbl), (x_), (y_));                                                          \
    lv_obj_set_align((lbl), LV_ALIGN_CENTER);                                                   \
    lv_label_set_text((lbl), (text_));                                                          \
    lv_obj_set_style_text_font((lbl), &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT); \
  } while (0)

#define UI_DROPDOWN_CREATE_DRIVER(obj, posx, posy, index, evt_cb, user_data)           \
  do {                                                                                 \
    (obj) = lv_dropdown_create(ui_mainpanel2);                                         \
    lv_dropdown_set_options((obj), (index));                                           \
    lv_obj_add_style((obj), &style_sel, LV_PART_MAIN);                                 \
    lv_obj_set_width((obj), 100);                                                      \
    lv_obj_align((obj), LV_ALIGN_CENTER, (posx), (posy));                              \
    lv_obj_add_event_cb((obj), (evt_cb), LV_EVENT_VALUE_CHANGED, (void *)(user_data)); \
    lv_dropdown_set_selected((obj), 1);                                                \
  } while (0)

static void op1_evt_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *obj = lv_event_get_target(e);

  ui_src_t src = (ui_src_t)(uintptr_t)lv_event_get_user_data(e);

  if (code == LV_EVENT_VALUE_CHANGED) {
    static char buf[32];
    lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
    // clang-format off
    lv_evt_send((app_evt_t){ 
      .type = APP_EVT_UI_VALUE_CHANGED, 
      .src = src, 
      .value = 0, 
      .str = buf });
  }
  // clang-format on
}

static void ui_common_evt_handler(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *obj = lv_event_get_target(e);

  ui_src_t src = (ui_src_t)(uintptr_t)lv_event_get_user_data(e);

  app_evt_t evt = { 0 };
  evt.src = src;

  static char buf[32] = { 0 };
  if (code == LV_EVENT_VALUE_CHANGED) {
    evt.type = APP_EVT_UI_VALUE_CHANGED;

    // dropdown이면 선택 index를 value에 넣기
    if (lv_obj_check_type(obj, &lv_dropdown_class)) {
      // evt.value = (int32_t)lv_dropdown_get_selected(obj);
      lv_dropdown_get_selected_str(obj, buf, sizeof(buf));
      evt.str = buf;
    } else if (lv_obj_check_type(obj, &lv_roller_class)) {
      evt.value = (int32_t)lv_roller_get_selected(obj);
    } else {
      evt.value = 0;
    }

    lv_evt_send(evt);
  } else if (code == LV_EVENT_CLICKED) {
    evt.type = APP_EVT_UI_CLICKED;
    evt.value = 1;
    lv_evt_send(evt);
  }
}

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x6114A1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Side_Panel = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Side_Panel, 195);
  lv_obj_set_height(ui_Side_Panel, 380);
  lv_obj_set_x(ui_Side_Panel, 4);
  lv_obj_set_y(ui_Side_Panel, 45);
  lv_obj_set_align(ui_Side_Panel, LV_ALIGN_LEFT_MID);
  lv_obj_clear_flag(ui_Side_Panel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Side_Panel, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Side_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_Side_Panel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_Side_Panel, lv_color_hex(0x9923E1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Side_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Side_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Side_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Side_Panel_Btn1 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn1, 100);
  lv_obj_set_height(ui_Side_Panel_Btn1, 50);
  lv_obj_set_x(ui_Side_Panel_Btn1, 0);
  lv_obj_set_y(ui_Side_Panel_Btn1, -120);
  lv_obj_set_align(ui_Side_Panel_Btn1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn1, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_Side_Panel_Btn1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Side_Panel_Btn1, lv_color_hex(0x46DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Side_Panel_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Side_Panel_Btn1, lv_color_hex(0x40773E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Side_Panel_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Main_Panel_Btn1_Label = lv_label_create(ui_Side_Panel_Btn1);
  lv_obj_set_width(ui_Main_Panel_Btn1_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn1_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn1_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn1_Label, "btn1");

  ui_Side_Panel_Btn2 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn2, 100);
  lv_obj_set_height(ui_Side_Panel_Btn2, 50);
  lv_obj_set_align(ui_Side_Panel_Btn2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

  ui_Main_Panel_Btn2_Label = lv_label_create(ui_Side_Panel_Btn2);
  lv_obj_set_width(ui_Main_Panel_Btn2_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn2_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn2_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn2_Label, "AGMO");

  ui_Side_Panel_Btn3 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn3, 100);
  lv_obj_set_height(ui_Side_Panel_Btn3, 50);
  lv_obj_set_x(ui_Side_Panel_Btn3, 0);
  lv_obj_set_y(ui_Side_Panel_Btn3, 120);
  lv_obj_set_align(ui_Side_Panel_Btn3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn3, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

  ui_Main_Panel_Btn3_Label = lv_label_create(ui_Side_Panel_Btn3);
  lv_obj_set_width(ui_Main_Panel_Btn3_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn3_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn3_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn3_Label, "btn3");

  ui_mainpanel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel1, 593);
  lv_obj_set_height(ui_mainpanel1, 380);
  lv_obj_set_x(ui_mainpanel1, -4);
  lv_obj_set_y(ui_mainpanel1, 45);
  lv_obj_set_align(ui_mainpanel1, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel1, lv_color_hex(0x12C9F1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label2 = lv_label_create(ui_mainpanel1);
  lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label2, -241);
  lv_obj_set_y(ui_Label2, -155);
  lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label2, "panel 1\n");
  lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mainPanel_btn_up = lv_btn_create(ui_mainpanel1);
  lv_obj_set_width(ui_mainPanel_btn_up, 100);
  lv_obj_set_height(ui_mainPanel_btn_up, 50);
  lv_obj_set_x(ui_mainPanel_btn_up, 0);
  lv_obj_set_y(ui_mainPanel_btn_up, -120);
  lv_obj_set_align(ui_mainPanel_btn_up, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_mainPanel_btn_up, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_mainPanel_btn_up, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_mainPanel_btn_up, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_mainPanel_btn_up, lv_color_hex(0x46DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainPanel_btn_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_mainPanel_btn_up, lv_color_hex(0x40773E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_mainPanel_btn_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mainpanel2 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel2, 593);
  lv_obj_set_height(ui_mainpanel2, 380);
  lv_obj_set_x(ui_mainpanel2, -4);
  lv_obj_set_y(ui_mainpanel2, 45);
  lv_obj_set_align(ui_mainpanel2, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel2, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label3 = lv_label_create(ui_mainpanel2);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label3, -250);
  lv_obj_set_y(ui_Label3, -130);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_label_set_text(ui_Label3, "RC_1");

  ui_Label3 = lv_label_create(ui_mainpanel2);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label3, -250);
  lv_obj_set_y(ui_Label3, -30);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_label_set_text(ui_Label3, "RC_2");

  ui_mainpanel3 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel3, 593);
  lv_obj_set_height(ui_mainpanel3, 380);
  lv_obj_set_x(ui_mainpanel3, -4);
  lv_obj_set_y(ui_mainpanel3, 45);
  lv_obj_set_align(ui_mainpanel3, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel3, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label5 = lv_label_create(ui_mainpanel3);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label5, -200);
  lv_obj_set_y(ui_Label5, -157);
  lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label5, "Wifi Configuration");

  ui_Panel3 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel3, 195);
  lv_obj_set_height(ui_Panel3, 85);
  lv_obj_set_x(ui_Panel3, 4);
  lv_obj_set_y(ui_Panel3, 4);
  lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel4 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel4, 195);
  lv_obj_set_height(ui_Panel4, 85);
  lv_obj_set_x(ui_Panel4, 203);
  lv_obj_set_y(ui_Panel4, 4);
  lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel5 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel5, 195);
  lv_obj_set_height(ui_Panel5, 85);
  lv_obj_set_x(ui_Panel5, -203);
  lv_obj_set_y(ui_Panel5, 4);
  lv_obj_set_align(ui_Panel5, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel6 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel6, 195);
  lv_obj_set_height(ui_Panel6, 85);
  lv_obj_set_x(ui_Panel6, -4);
  lv_obj_set_y(ui_Panel6, 4);
  lv_obj_set_align(ui_Panel6, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label1 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label1, -258);
  lv_obj_set_y(ui_Label1, -191);
  lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label1, "Light");
  lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label1, LV_FONT_MONTSERRAT_22, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2105472862, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2105472862, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_77785195, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_77785195, NULL);
  lv_obj_set_width(ui_ImgButton1, 100);
  lv_obj_set_height(ui_ImgButton1, 100);
  lv_obj_set_x(ui_ImgButton1, -350);
  lv_obj_set_y(ui_ImgButton1, -194);
  lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

  lv_obj_add_event_cb(ui_Side_Panel_Btn1, ui_event_Side_Panel_Btn1, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Side_Panel_Btn2, ui_event_Side_Panel_Btn2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Side_Panel_Btn3, ui_event_Side_Panel_Btn3, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

  UI_LABEL_CREATE(ui_Label_10, ui_mainpanel2, -250, -100, "UD_1");
  UI_LABEL_CREATE(ui_Label_11, ui_mainpanel2, -180, -100, "UD_2");
  UI_LABEL_CREATE(ui_Label_12, ui_mainpanel2, -110, -100, "UD_3");
  UI_LABEL_CREATE(ui_Label_13, ui_mainpanel2, -40, -100, "UD_4");
  UI_LABEL_CREATE(ui_Label_volt_RC1_M1, ui_mainpanel2, 50, -100, "RC1_M1");
  UI_LABEL_CREATE(ui_Label_volt_RC1_M2, ui_mainpanel2, 150, -100, "RC1_M2");
  UI_LABEL_CREATE(ui_Label_14, ui_mainpanel2, -250, 0, "UD_5");
  UI_LABEL_CREATE(ui_Label_15, ui_mainpanel2, -180, 0, "UD_6");
  UI_LABEL_CREATE(ui_Label_16, ui_mainpanel2, -110, 0, "UD_7");
  UI_LABEL_CREATE(ui_Label_17, ui_mainpanel2, -40, 0, "UD_8");
  UI_LABEL_CREATE(ui_Label_18, ui_mainpanel2, -250, 50, "UD_9");
  UI_LABEL_CREATE(ui_Label_volt_RC2_M1, ui_mainpanel2, 50, 0, "RC1_M1");
  UI_LABEL_CREATE(ui_Label_volt_RC2_M2, ui_mainpanel2, 150, 0, "RC1_M2");

  /*A style to make the selected option larger*/
  static lv_style_t style_sel;
  lv_style_init(&style_sel);
  lv_style_set_text_font(&style_sel, &lv_font_montserrat_16);

  const char *select_driver = "RC1\nRC2\nBoth";
  const char *target_volt = "0V\n1V\n2V\n3V\n4V\n5V\n6V\n7V\n8V\n9V\n10V\n11V\n12V";
  const char *period_set = "100ms\n200ms\n300ms\n400ms\n500ms\n600ms\n700ms\n800ms\n900ms\n";
  const char *run = "Run\nStop";

  /*A roller on the middle with center aligned text, and auto (default) width*/
  ui_s_driver = lv_dropdown_create(ui_mainpanel2);
  lv_dropdown_set_options(ui_s_driver, select_driver);
  lv_obj_add_style(ui_s_driver, &style_sel, LV_PART_MAIN);
  lv_obj_set_width(ui_s_driver, 80);
  lv_obj_align(ui_s_driver, LV_ALIGN_CENTER, -220, 150);
  lv_obj_add_event_cb(ui_s_driver, op1_evt_handler, LV_EVENT_VALUE_CHANGED, (void *)UI_SRC_DRIVER_DD);
  lv_dropdown_set_selected(ui_s_driver, 1);

  UI_DROPDOWN_CREATE_DRIVER(ui_s_ud_1, -100, 150, target_volt, ui_common_evt_handler, UI_SRC_TARGET_VOLT);
  UI_DROPDOWN_CREATE_DRIVER(ui_s_ud_1, 20, 150, period_set, ui_common_evt_handler, UI_SRC_MODE_PERIOD_SET);
  UI_DROPDOWN_CREATE_DRIVER(ui_s_ud_1, 140, 150, run, ui_common_evt_handler, UI_SRC_BTN_RUN);
}
