// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x6114A1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Side_Panel = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Side_Panel, 195);
  lv_obj_set_height(ui_Side_Panel, 380);
  lv_obj_set_x(ui_Side_Panel, 4);
  lv_obj_set_y(ui_Side_Panel, 45);
  lv_obj_set_align(ui_Side_Panel, LV_ALIGN_LEFT_MID);
  lv_obj_clear_flag(ui_Side_Panel, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Side_Panel, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Side_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_Side_Panel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(ui_Side_Panel, lv_color_hex(0x9923E1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(ui_Side_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(ui_Side_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(ui_Side_Panel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Side_Panel_Btn1 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn1, 100);
  lv_obj_set_height(ui_Side_Panel_Btn1, 50);
  lv_obj_set_x(ui_Side_Panel_Btn1, 0);
  lv_obj_set_y(ui_Side_Panel_Btn1, -120);
  lv_obj_set_align(ui_Side_Panel_Btn1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn1, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
  lv_obj_set_style_radius(ui_Side_Panel_Btn1, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Side_Panel_Btn1, lv_color_hex(0x46DD19), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Side_Panel_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Side_Panel_Btn1, lv_color_hex(0x40773E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Side_Panel_Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Main_Panel_Btn1_Label = lv_label_create(ui_Side_Panel_Btn1);
  lv_obj_set_width(ui_Main_Panel_Btn1_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn1_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn1_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn1_Label, "btn1");

  ui_Side_Panel_Btn2 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn2, 100);
  lv_obj_set_height(ui_Side_Panel_Btn2, 50);
  lv_obj_set_align(ui_Side_Panel_Btn2, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn2, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

  ui_Main_Panel_Btn2_Label = lv_label_create(ui_Side_Panel_Btn2);
  lv_obj_set_width(ui_Main_Panel_Btn2_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn2_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn2_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn2_Label, "btn2");

  ui_Side_Panel_Btn3 = lv_btn_create(ui_Side_Panel);
  lv_obj_set_width(ui_Side_Panel_Btn3, 100);
  lv_obj_set_height(ui_Side_Panel_Btn3, 50);
  lv_obj_set_x(ui_Side_Panel_Btn3, 0);
  lv_obj_set_y(ui_Side_Panel_Btn3, 120);
  lv_obj_set_align(ui_Side_Panel_Btn3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Side_Panel_Btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
  lv_obj_clear_flag(ui_Side_Panel_Btn3, LV_OBJ_FLAG_SCROLLABLE);     /// Flags

  ui_Main_Panel_Btn3_Label = lv_label_create(ui_Side_Panel_Btn3);
  lv_obj_set_width(ui_Main_Panel_Btn3_Label, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Main_Panel_Btn3_Label, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_align(ui_Main_Panel_Btn3_Label, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Main_Panel_Btn3_Label, "btn3");

  ui_mainpanel1 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel1, 593);
  lv_obj_set_height(ui_mainpanel1, 380);
  lv_obj_set_x(ui_mainpanel1, -4);
  lv_obj_set_y(ui_mainpanel1, 45);
  lv_obj_set_align(ui_mainpanel1, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel1, lv_color_hex(0x12C9F1), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label2 = lv_label_create(ui_mainpanel1);
  lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label2, -241);
  lv_obj_set_y(ui_Label2, -155);
  lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label2, "panel 1\n");
  lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x030000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_mainpanel2 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel2, 593);
  lv_obj_set_height(ui_mainpanel2, 380);
  lv_obj_set_x(ui_mainpanel2, -4);
  lv_obj_set_y(ui_mainpanel2, 45);
  lv_obj_set_align(ui_mainpanel2, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel2, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label3 = lv_label_create(ui_mainpanel2);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label3, -237);
  lv_obj_set_y(ui_Label3, -151);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label3, "panel2");

  ui_mainpanel3 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_mainpanel3, 593);
  lv_obj_set_height(ui_mainpanel3, 380);
  lv_obj_set_x(ui_mainpanel3, -4);
  lv_obj_set_y(ui_mainpanel3, 45);
  lv_obj_set_align(ui_mainpanel3, LV_ALIGN_RIGHT_MID);
  lv_obj_clear_flag(ui_mainpanel3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_mainpanel3, lv_color_hex(0xE2ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_mainpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label5 = lv_label_create(ui_mainpanel3);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label5, -200);
  lv_obj_set_y(ui_Label5, -157);
  lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label5, "Wifi Configuration");

  ui_Panel3 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel3, 195);
  lv_obj_set_height(ui_Panel3, 85);
  lv_obj_set_x(ui_Panel3, 4);
  lv_obj_set_y(ui_Panel3, 4);
  lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel4 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel4, 195);
  lv_obj_set_height(ui_Panel4, 85);
  lv_obj_set_x(ui_Panel4, 203);
  lv_obj_set_y(ui_Panel4, 4);
  lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel5 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel5, 195);
  lv_obj_set_height(ui_Panel5, 85);
  lv_obj_set_x(ui_Panel5, -203);
  lv_obj_set_y(ui_Panel5, 4);
  lv_obj_set_align(ui_Panel5, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel6 = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_Panel6, 195);
  lv_obj_set_height(ui_Panel6, 85);
  lv_obj_set_x(ui_Panel6, -4);
  lv_obj_set_y(ui_Panel6, 4);
  lv_obj_set_align(ui_Panel6, LV_ALIGN_TOP_RIGHT);
  lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_border_side(ui_Panel6, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label1 = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_Label1, -258);
  lv_obj_set_y(ui_Label1, -191);
  lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label1, "Light");
  lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ImgButton1 = lv_imgbtn_create(ui_Screen1);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2105472862, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_2105472862, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_77785195, NULL);
  lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_77785195, NULL);
  lv_obj_set_width(ui_ImgButton1, 100);
  lv_obj_set_height(ui_ImgButton1, 100);
  lv_obj_set_x(ui_ImgButton1, -350);
  lv_obj_set_y(ui_ImgButton1, -194);
  lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

  lv_obj_add_event_cb(ui_Side_Panel_Btn1, ui_event_Side_Panel_Btn1, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Side_Panel_Btn2, ui_event_Side_Panel_Btn2, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_Side_Panel_Btn3, ui_event_Side_Panel_Btn3, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
}
