// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Side_Panel;
void ui_event_Side_Panel_Btn1(lv_event_t *e);
lv_obj_t *ui_Side_Panel_Btn1;
lv_obj_t *ui_Main_Panel_Btn1_Label;
void ui_event_Side_Panel_Btn2(lv_event_t *e);
lv_obj_t *ui_Side_Panel_Btn2;
lv_obj_t *ui_Main_Panel_Btn2_Label;
void ui_event_Side_Panel_Btn3(lv_event_t *e);
lv_obj_t *ui_Side_Panel_Btn3;
lv_obj_t *ui_Main_Panel_Btn3_Label;
lv_obj_t *ui_mainpanel1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_mainpanel2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_mainpanel3;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Label1;
void ui_event_ImgButton1(lv_event_t *e);
lv_obj_t *ui_ImgButton1;
lv_obj_t *ui____initial_actions0;

lv_obj_t *ui_mainPanel_btn_up;

// CAN TEST

lv_obj_t *ui_Label_10;  // user_data 1
lv_obj_t *ui_Label_11;  // user_data 2
lv_obj_t *ui_Label_12;  // user_data 3
lv_obj_t *ui_Label_13;  // user_data 4
lv_obj_t *ui_Label_14;  // user_data 5
lv_obj_t *ui_Label_15;  // user_data 6
lv_obj_t *ui_Label_16;  // user_data 7
lv_obj_t *ui_Label_17;  // user_data 8
lv_obj_t *ui_Label_18;  // user_data 9
lv_obj_t *ui_Label_19;  //
lv_obj_t *ui_Label_20;  //

lv_obj_t *ui_Label_volt_RC1_M1;  // checked motor voltage value for rc1 M1
lv_obj_t *ui_Label_volt_RC1_M2;  //
lv_obj_t *ui_Label_volt_RC2_M1;  //
lv_obj_t *ui_Label_volt_RC2_M2;  //

lv_obj_t *ui_s_driver;
lv_obj_t *ui_s_ud_1;
lv_obj_t *ui_s_ud_3;
lv_obj_t *ui_s_ud_4;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Side_Panel_Btn1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_flag_modify(ui_mainpanel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
  }
}
void ui_event_Side_Panel_Btn2(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_flag_modify(ui_mainpanel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
  }
}
void ui_event_Side_Panel_Btn3(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_flag_modify(ui_mainpanel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_mainpanel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
  }
}
void ui_event_ImgButton1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_checked_set_text_value(ui_Label1, target, "a", "b");
    _ui_state_modify(ui_ImgButton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                            false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_Screen1);
}
