// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#ifndef _WIFI_MANUAL_SQUARELINE_PROJECT_UI_H
#define _WIFI_MANUAL_SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Side_Panel;
void ui_event_Side_Panel_Btn1( lv_event_t * e);
extern lv_obj_t *ui_Side_Panel_Btn1;
extern lv_obj_t *ui_Main_Panel_Btn1_Label;
void ui_event_Side_Panel_Btn2( lv_event_t * e);
extern lv_obj_t *ui_Side_Panel_Btn2;
extern lv_obj_t *ui_Main_Panel_Btn2_Label;
void ui_event_Side_Panel_Btn3( lv_event_t * e);
extern lv_obj_t *ui_Side_Panel_Btn3;
extern lv_obj_t *ui_Main_Panel_Btn3_Label;
extern lv_obj_t *ui_mainpanel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_mainpanel2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_mainpanel3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label1;
void ui_event_ImgButton1( lv_event_t * e);
extern lv_obj_t *ui_ImgButton1;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_2105472862);   // assets/Icon-Small-50@2x.png
LV_IMG_DECLARE( ui_img_77785195);   // assets/Icon-Small-50@2x 복사본.png

LV_FONT_DECLARE( ui_font_Display16);
LV_FONT_DECLARE( ui_font_Display24);
LV_FONT_DECLARE( ui_font_Display40);
LV_FONT_DECLARE( ui_font_Display90);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
