// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#ifndef _WIFI_MANUAL_SQUARELINE_PROJECT_UI_COMP_HOOK_H
#define _WIFI_MANUAL_SQUARELINE_PROJECT_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Screen2_Keyboard1_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
