// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#include "../ui.h"


// COMPONENT Screen2 Keyboard1

lv_obj_t *ui_Screen2_Keyboard1_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Screen2_Keyboard1;
cui_Screen2_Keyboard1 = lv_keyboard_create(comp_parent);
lv_keyboard_set_mode(cui_Screen2_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( cui_Screen2_Keyboard1, 300);
lv_obj_set_height( cui_Screen2_Keyboard1, 141);
lv_obj_set_x( cui_Screen2_Keyboard1, -77 );
lv_obj_set_y( cui_Screen2_Keyboard1, 77 );
lv_obj_set_align( cui_Screen2_Keyboard1, LV_ALIGN_CENTER );

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SCREEN2_KEYBOARD1_NUM);
children[UI_COMP_SCREEN2_KEYBOARD1_SCREEN2_KEYBOARD1] = cui_Screen2_Keyboard1;
lv_obj_add_event_cb(cui_Screen2_Keyboard1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Screen2_Keyboard1, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Screen2_Keyboard1_create_hook(cui_Screen2_Keyboard1);
return cui_Screen2_Keyboard1; 
}

