// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: wifi_manual_SquareLine_Project

#include "../ui.h"

void ui_comp_Screen2_Keyboard1_create_hook( lv_obj_t * comp)
{
}
