// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#include "freertos/FreeRTOS.h"
#include "ui.h"
#include <stdio.h>
#include "ui_helpers.h"
#include "scale_read_485.h"
#include "log.h"
#include "i2s_speaker.h"
#include "syscfg.h"
#include "sys_config.h"
#include "config.h"
#include "time.h"
#include "main.h"

static const char *TAG = "UI_LVGL";

static void ui_ListSelectScreen_List_Panel_PageBuilder();

///////////////////// VARIABLES ////////////////////
// SCREEN: ui_indicator_model_select_screen
lv_obj_t *ui_Indicator_Model_Select_Screen;
lv_obj_t *indicator_list;

// SCREEN: ui_time_set_screen
lv_obj_t *ui_Time_Date_Set_Screen;
lv_obj_t *ui_Time_Date_Set_Screen_Time_Label;
lv_obj_t *ui_Time_Date_Set_Screen_Date_Label;

// SCREEN: ui_main_Screen
lv_obj_t *ui_judge_color_Screen;
lv_obj_t *ui_judge_color_ScreenPanel;

// SCREEN: ui_main_Screen
lv_obj_t *ui_Main_Screen;
lv_obj_t *ui_MainScreenPanel;
lv_obj_t *ui_MainScreenBtn1;
lv_obj_t *ui_MainScreenBtn1Label;
lv_obj_t *ui_MainScreenBtn2;
lv_obj_t *ui_MainScreenBtn1Label2;
lv_obj_t *ui_main_scr_Device_Id_Area_Label;
lv_obj_t *ui_main_scr_Indicator_Model_Label;
lv_obj_t *ui_main_scr_Time_Date_Label;

// SCREEN : ui_device_id_reg_screen
lv_obj_t *ui_device_id_reg_screen;

// SCREEN: ui_mode_2_Screen
lv_obj_t *ui_mode_2_scr;
lv_obj_t *ui_mode_2_scr_Panel1;
lv_obj_t *ui_mode_2_scr_Panel1_Current_Weight_Label;
lv_obj_t *ui_mode_2_scr_Panel1_Current_Count_Label;
lv_obj_t *ui_mode_2_scr_Panel1_Zero_Point_Label;
lv_obj_t *ui_mode_2_scr_Panel1_Stable_Point_Label;
lv_obj_t *ui_mode_2_scr_Panel1_Tare_Point_Label;
lv_obj_t *ui_mode_2_scr_Panel1_Amount_Value_Label;

// SCREEN: ui_Screen1

lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Screen1_Panel1_Current_Weight_Label;
lv_obj_t *ui_Screen1_Panel1_Current_Count_Label;
lv_obj_t *ui_Screen1_Setting_Btn_Label;
lv_obj_t *ui_led1;
lv_obj_t *ui_led2;
lv_obj_t *ui_led3;
lv_obj_t *ui_Screen1_over_Label;
lv_obj_t *ui_Screen1_normal_Label;
lv_obj_t *ui_Screen1_lack_Label;
lv_obj_t *ui_Screen1_Setting_Btn;
lv_obj_t *ui_Screen1_Panel1_Zero_Point_Label;
lv_obj_t *ui_Screen1_Panel1_Stable_Point_Label;
lv_obj_t *ui_Screen1_Panel1_Tare_Point_Label;
lv_obj_t *ui_Screen1_Amount_Value_Label;
lv_obj_t *ui_Screen1_Prod_Num_Label;
lv_obj_t *ui_Screen1_Upper_Value_Label;
lv_obj_t *ui_Screen1_Lower_Value_Label;
lv_obj_t *ui_Screen1_Judge_Comfirm_Btn;

// lv_obj_t *ui_Recently_Msg_Box_Panel;
// lv_obj_t *ui_Recently_Msg_Box_Panel_Label;

// SCREEN: ui_Screen2
lv_obj_t *ui_Screen2;

// SCREEN: ui_list_select
lv_obj_t *ui_list_select;
lv_obj_t *ui_ListSelectScreen_List_Panel;
lv_obj_t *ui_ListSelectScreen_Comfirm_Panel;
lv_obj_t *ui_ListSelectScreen_Comfirm_Label;
lv_obj_t *ui_ListSelectScreen_Comfirm_Btn;
lv_obj_t *ui_ListSelectScreen_Comfirm_Btn_Label;
lv_obj_t *ui_ListSelectScreen_Delete_Btn;
lv_obj_t *ui_ListSelectScreen_Delete_Btn_Label;

float upper_weight_value = 0.0;
float lower_weight_value = 0.0;
int prod_num_value = 0;
float renge_weight_value = 0.0;
float amount_weight_value = 0.0;

int judge_total_count = 0;
int judge_over_count = 0;
int judge_normal_count = 0;
int judge_lack_count = 0;
screen_mode_t curr_mode;
ui_event_ids_t ui_event;
ui_internal_data_ctx_t ui_data_ctx;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

static lv_style_t style_clock;
char timeString[9] = { 0 };
char dateString[30] = { 0 };
static char time_date_string[50] = { 0 };

char s_tare_set_value[10] = { 0 };

bool normal_event_flag = false;
bool over_event_flag = false;
bool nuder_event_flag = false;
bool copying_flag = true;
bool usb_copy_success_flag = true;
bool weight_tare_flag = false;

static lv_obj_t *s_btn[PROD_NUM];
static char saved_data[PROD_NUM][MAX_DATA_LEN] = {
  0,
};
static int btn_num = PROD_NUM;
static char string_empty[100];

static char indicator_model_buf[20] = { 0 };
indicator_model_t indicator_model;

int (*weight_zero_command)();

const char log_table_index[] = { "TIME,PID,TOTAL,OVER,NORMAL,UNDER\n" };

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

inline void OBJ_TEXT_SET_LABEL(lv_obj_t *e, const char *txt) {
  lv_label_set_text(e, txt);
}

void ui_event_Screen1_List_Select_Button(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_list_select, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_list_select_screen_init);
    ui_ListSelectScreen_List_Panel_PageBuilder();
  }
}

static void ui_ListSelectScreen_List_Panel_PageBuilder() {
  uint32_t i = 0;
  for (i = 0; i < btn_num; i++) {
    char key[10] = { 0 };

    if (s_btn[i]) {
      LOGI(TAG, "obj delete = [%p]", s_btn[i]);
      lv_obj_remove_event_cb(s_btn[i], ui_ListSelectScreen_List_Panel_Btn_e_handler);
      lv_obj_del(s_btn[i]);  // There is a common delete function for all object types
      s_btn[i] = NULL;
    }

    memset(&saved_data[i], 0x00, sizeof(saved_data[i]));
    snprintf(key, sizeof(key), "Prod%02ld", i);
    syscfg_get(CFG_DATA, key, saved_data[i], sizeof(saved_data[i]));

    s_btn[i] = lv_btn_create(ui_ListSelectScreen_List_Panel);

    if (s_btn[i]) {
      LOGI(TAG, "btn[%d] = %p", i, s_btn[i]);
      LOGI(TAG, "saved_data = %s", saved_data[i]);

      lv_obj_set_size(s_btn[i], 120, 70);
      lv_obj_set_style_bg_color(s_btn[i], lv_color_hex(0x232D3F), LV_PART_MAIN | LV_STATE_DEFAULT);

      lv_obj_add_event_cb(s_btn[i], ui_ListSelectScreen_List_Panel_Btn_e_handler, LV_EVENT_ALL, saved_data[i]);
      lv_obj_t *label = lv_label_create(s_btn[i]);

      if (strlen(saved_data[i])) {  // Check registered values.
        // data format : 01.upper:10.000,lower:10.000
        char *ptr = saved_data[i];
        if (i == 3) {
          lv_label_set_text_fmt(label, "품번 %.2s\n상한:%.6s\n하한:%.6s", ptr, ptr + 9, ptr + 22);
          lv_obj_set_style_text_font(label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
          lv_obj_clear_flag(s_btn[i], LV_OBJ_FLAG_SNAPABLE);
        } else {
          lv_label_set_text_fmt(label, "품번 %.2s\n상한:%.6s\n하한:%.6s", ptr, ptr + 9, ptr + 22);
          lv_obj_set_style_text_font(label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        lv_obj_center(label);
      } else {
        lv_label_set_text_fmt(label, " ");
      }
    } else {
      LOGI(TAG, "Failed to create button!!!");
    }
  }
  lv_obj_update_snap(ui_ListSelectScreen_List_Panel, LV_ANIM_ON);
}

void ui_ListSelectScreen_List_Panel_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char *value = lv_event_get_user_data(e);
  char data[MAX_DATA_LEN] = { 0 };
  char s_empty[80] = { 0 };
  if (event_code == LV_EVENT_CLICKED) {
    for (int i = 0; i < btn_num; i++) {
      if (s_btn[i] == target) {
        LOGI(TAG, "btn[%d] = %p, target = %p", i, s_btn[i], target);
        lv_obj_set_style_bg_color(target, lv_palette_main(LV_PALETTE_RED), 0);  // color change of selected btn
        // break;
      } else {
        lv_obj_set_style_bg_color(s_btn[i], lv_color_hex(0x232D3F), 0);
      }
    }
    if (value) {
      snprintf(data, sizeof(data), "%s", value);
      LOGI(TAG, "selected btn : %s", value);
    }
    if (strlen(data)) {
      snprintf(s_empty, sizeof(s_empty), "품번:%.2s, 상한:%.6s, 하한:%.6s", &data[0], &data[9], &data[22]);
    }
    lv_label_set_text(ui_ListSelectScreen_Comfirm_Label, s_empty);
    lv_obj_set_style_text_font(ui_ListSelectScreen_Comfirm_Label, &NanumBar18, LV_PART_MAIN | LV_STATE_DEFAULT);

    memset(string_empty, 0x00, sizeof(string_empty));
    memcpy(string_empty, data, strlen(value));
    LOGI(TAG, "Comfirm_Label_data : %s", data);
  }
}

void ui_ListSelectScreen_Delete_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  // char *value = lv_event_get_user_data(e);
  char s_key[10] = { 0 };
  if (event_code == LV_EVENT_CLICKED) {
    LOGI(TAG, "Delete value : %s", string_empty);
    if (strlen(string_empty)) {
      snprintf(s_key, sizeof(s_key), "Prod%.2s", string_empty);
      syscfg_unset(CFG_DATA, s_key);
      memset(string_empty, 0x00, sizeof(string_empty));
    }
    _ui_screen_change(&ui_list_select, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_list_select_screen_init);
    ui_ListSelectScreen_List_Panel_PageBuilder();
  }
}

void ui_ListSelectScreen_Comfirm_Btn_e_handler(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  char s_upper_weight_value[10] = { 0 };
  char s_lower_weight_value[10] = { 0 };
  char s_prod_num_value[10] = { 0 };
  if (event_code == LV_EVENT_CLICKED) {
    /*Todo*/
    // set to selected value loop
    LOGI(TAG, "Set value : %s", string_empty);
    if (strlen(string_empty)) {
      // data format : 01.upper:10.000,lower:10.000
      snprintf(s_upper_weight_value, sizeof(s_upper_weight_value), "%.6s", string_empty + 9);
      snprintf(s_lower_weight_value, sizeof(s_lower_weight_value), "%.6s", string_empty + 22);
      snprintf(s_prod_num_value, sizeof(s_prod_num_value), "%.2s", string_empty);
      LOGI(TAG, "s_upper_weight_value : %s", s_upper_weight_value);
      LOGI(TAG, "s_lower_weight_value : %s", s_lower_weight_value);
      LOGI(TAG, "s_prod_num_value : %s", s_prod_num_value);

      memset(string_empty, 0x00, sizeof(string_empty));

      sscanf(s_upper_weight_value, "%f", &upper_weight_value);
      sscanf(s_lower_weight_value, "%f", &lower_weight_value);
      prod_num_value = atoi(s_prod_num_value);

      lv_event_send(ui_Screen1_Upper_Value_Label, LV_EVENT_READY, NULL);
      lv_event_send(ui_Screen1_Lower_Value_Label, LV_EVENT_READY, NULL);
      lv_event_send(ui_Screen1_Prod_Num_Label, LV_EVENT_READY, NULL);

      _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    } else {
      _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    }
  }
}

static void usb_event_cb(lv_event_t *e) {
  lv_obj_t *obj = lv_event_get_current_target(e);
  LOGI(TAG, "Button %s clicked", lv_msgbox_get_active_btn_text(obj));
  if (strcmp(lv_msgbox_get_active_btn_text(obj), "Close") == 0) {
    lv_msgbox_close(obj);
  }
}

void logic_timer_cb(lv_timer_t *timer) {
  char s_weight[20] = { 0 };
  char s_amount_count[20] = { 0 };
  char s_judge_total_count[20] = { 0 };

  float weight = 0;
  int weight_float = 0;
  float tare_weight = 0.0;
  bool trash_fileter_flag = false;
  Common_data_t indicator_data = { 0 };

  switch (indicator_model) {
    case MODEL_NONE: LOGE(TAG, "No target indicator model!"); break;

    case MODEL_CAD_WTM500:
      memset(&indicator_data, 0x00, sizeof(indicator_data));
      indicator_WTM_500_data(&indicator_data);
      // LOGE(TAG, "indicator data : %d", atoi(indicator_data.weight_data));
      //   taking float value using %f format specifier for
      sscanf(indicator_data.weight_data, "%f", &weight);
      snprintf(s_weight, sizeof(s_weight), "%.3f", weight);
      break;
    case MODEL_BAYKON_BX11:
      memset(&indicator_data, 0x00, sizeof(indicator_data));
      indicator_BX11_data(&indicator_data);
      // LOGE(TAG, "indicator data : %d", atoi(indicator_data.weight_data));
      //  LOGI(TAG, "heap size : %d", esp_get_free_heap_size());
      //  LOGI(TAG, "heap size of internal %d", esp_get_free_internal_heap_size());

      switch (indicator_data.DP) {
        case DP_100:
          // weight = (float)(atoi(indicator_data.weight_data) * 100);
          // LOGI(TAG, "DP_100 : %f", weight);
          // snprintf(s_weight, sizeof(s_weight), "%d", (int)weight);
          // snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_10:
          weight = (float)(atoi(indicator_data.weight_data) * 10);
          snprintf(s_weight, sizeof(s_weight), "%d", (int)weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_1:
          weight = (float)(atoi(indicator_data.weight_data) * 1);
          snprintf(s_weight, sizeof(s_weight), "%d", (int)weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_0_1:
          weight = (float)(atoi(indicator_data.weight_data) * 0.1);
          snprintf(s_weight, sizeof(s_weight), "%.1f", weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_0_01:
          weight = (float)(atoi(indicator_data.weight_data) * 0.01);
          snprintf(s_weight, sizeof(s_weight), "%.2f", weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_0_001:
          weight = (float)(atoi(indicator_data.weight_data) * 0.001);
          snprintf(s_weight, sizeof(s_weight), "%.3f", weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_0_0001:
          weight = (float)(atoi(indicator_data.weight_data) * 0.0001);
          snprintf(s_weight, sizeof(s_weight), "%.4f", weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        case DP_0_00001:
          weight = (float)(atoi(indicator_data.weight_data) * 0.00001);
          snprintf(s_weight, sizeof(s_weight), "%.5f", weight);
          snprintf(s_amount_count, sizeof(s_amount_count), "%03d", (int)(weight / amount_weight_value));
          break;
        default: break;
      }
    default: break;
  }

  snprintf(s_judge_total_count, sizeof(s_judge_total_count), "%03d", judge_total_count);

  /* This is a function that changes the color of the notification button to green
     so that you can save the data completed so far by pressing the green “Complete” button.
  */
  if (judge_total_count > 0) {
    lv_obj_set_style_bg_color(ui_Screen1_Judge_Comfirm_Btn, lv_palette_main(LV_PALETTE_LIGHT_GREEN), LV_PART_MAIN);
  } else {
    lv_obj_set_style_bg_color(ui_Screen1_Judge_Comfirm_Btn, lv_color_hex(0xff0060), LV_PART_MAIN | LV_STATE_DEFAULT);
  }

  if (is_usb_copying(USB_COPY_SUCCESS) && usb_copy_success_flag) {
    usb_copy_success_flag = false;
    static const char *btns[] = { "Close", "" };
    lv_obj_t *mbox6 = lv_msgbox_create(NULL, "USB_COPY!", "success!", btns, true);
    lv_obj_add_event_cb(mbox6, usb_event_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_center(mbox6);
  }
  if (!is_usb_disconnect_notify()) {
    // usb_copy_success_flag = true;
    usb_copy_success_flag = true;
  }

  // checking the trash data from 485 receive data format
  if (indicator_data.event[STATE_TRASH_CHECK_EVENT] == STATE_TRASH_CHECK_EVENT) {
    trash_fileter_flag = true;
  } else {
    trash_fileter_flag = false;
  }

  // display to weight status

  /*stable state set display */
  if (trash_fileter_flag) {
    if (indicator_data.event[STATE_STABLE_EVENT] == STATE_STABLE_EVENT) {
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Stable_Point_Label, lv_color_hex(0x0d00ff),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Stable_Point_Label, lv_color_hex(0x0d00ff),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Stable_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Stable_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (indicator_data.event[STATE_ZERO_EVENT] == STATE_ZERO_EVENT) {
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Zero_Point_Label, lv_color_hex(0xc70039),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Zero_Point_Label, lv_color_hex(0xc70039),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Zero_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Zero_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    if (indicator_data.event[STATE_TARE_EVENT] == STATE_TARE_EVENT) {
      weight_tare_flag = true;
      sscanf(s_tare_set_value, "%f", &tare_weight);
      tare_weight *= -1;
      LOGI(TAG, "tare string value : %s", s_tare_set_value);
      // LOGI(TAG, "tare float value : %f", tare_weight);
      // LOGI(TAG, "weight float value : %f", weight);
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Tare_Point_Label, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Tare_Point_Label, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
      weight_tare_flag = false;
      lv_obj_set_style_text_color(ui_Screen1_Panel1_Tare_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
      lv_obj_set_style_text_color(ui_mode_2_scr_Panel1_Tare_Point_Label, lv_color_hex(0xe9e9e9),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    }
  }

  switch (ui_data_ctx.curr_mode) {
    case MODE_1:
      // no show to under zero and over 100kg
      if (trash_fileter_flag) {
        if (indicator_data.event[STATE_SIGN_EVENT] == STATE_SIGN_EVENT) {
          lv_label_set_text(ui_Screen1_Panel1_Current_Weight_Label, "UNKNOWN");
          lv_label_set_text(ui_Screen1_Panel1_Current_Count_Label, "\0");
          // processed when in state tare
          if (weight_tare_flag && tare_weight == weight) {
            over_event_flag = false;
            nuder_event_flag = false;
            normal_event_flag = false;
            lv_led_off(ui_led1);
            lv_led_off(ui_led2);
            lv_led_off(ui_led3);
          }
        } else if (weight >= (float)100.0) {
          lv_label_set_text(ui_Screen1_Panel1_Current_Weight_Label, "OVERLOAD");
          lv_label_set_text(ui_Screen1_Panel1_Current_Count_Label, "\0");
        } else {
          lv_label_set_text(ui_Screen1_Panel1_Current_Weight_Label, s_weight);
          lv_label_set_text(ui_Screen1_Panel1_Current_Count_Label, s_judge_total_count);
        }

        // upper weight check
        // pord_num 0 is a special method that does not determine whether it works or not.
        if ((float)0.0 == upper_weight_value || (float)0.0 == lower_weight_value || 0 == prod_num_value) {
        } else {
          if (upper_weight_value < weight && !over_event_flag) {
            if (indicator_data.event[STATE_STABLE_EVENT] == STATE_STABLE_EVENT) {
              judge_total_count++;
              judge_over_count++;
              push(&ui_data_ctx.stack_root, JUDGE_OVER);
              lv_label_set_text_fmt(ui_Screen1_over_Label, "초과 %d", judge_over_count);
              lv_led_on(ui_led1);
              // lv_obj_set_style_bg_color(ui_judge_color_ScreenPanel, lv_palette_main(LV_PALETTE_RED), LV_PART_MAIN);
              // _ui_screen_change(&ui_judge_color_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0,
              //                   &ui_judge_color_screen_init);  //

              led_1_ctrl(1);
              over_volume();

              // Clear all judgments
              over_event_flag = VOLUME_CONTIUNE ? true : false;  // 계속나오게.. 요청사항
              nuder_event_flag = true;
              normal_event_flag = true;
              lv_led_off(ui_led2);
              lv_led_off(ui_led3);
            }
          }

          // nuder weight check
          // Judgment minimum weight 100g
          if ((float)0.1 < weight && lower_weight_value > weight && !nuder_event_flag && weight > 0) {
            if (indicator_data.event[STATE_STABLE_EVENT] == STATE_STABLE_EVENT) {
              judge_total_count++;
              judge_lack_count++;
              push(&ui_data_ctx.stack_root, JUDGE_LACK);
              lv_label_set_text_fmt(ui_Screen1_lack_Label, "부족 %d", judge_lack_count);
              lv_led_on(ui_led3);
              // lv_obj_set_style_bg_color(ui_judge_color_ScreenPanel, lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
              // _ui_screen_change(&ui_judge_color_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0,
              //                   &ui_judge_color_screen_init);  //
              led_3_ctrl(1);
              lack_volume();
              // Clear all judgments
              over_event_flag = true;
              nuder_event_flag = VOLUME_CONTIUNE ? true : false;
              normal_event_flag = true;
              lv_led_off(ui_led1);
              lv_led_off(ui_led2);
            }
          }

          // // success weight check
          if (lower_weight_value <= weight && upper_weight_value > weight && !normal_event_flag) {
            if (indicator_data.event[STATE_STABLE_EVENT] == STATE_STABLE_EVENT) {
              judge_total_count++;
              judge_normal_count++;
              push(&ui_data_ctx.stack_root, JUDGE_NORMAL);
              lv_label_set_text_fmt(ui_Screen1_normal_Label, "정상 %d", judge_normal_count);
              lv_led_on(ui_led2);
              // lv_obj_set_style_bg_color(ui_judge_color_ScreenPanel, lv_palette_main(LV_PALETTE_LIGHT_GREEN),
              //                           LV_PART_MAIN);
              // _ui_screen_change(&ui_judge_color_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0,
              //                   &ui_judge_color_screen_init);  //
              led_2_ctrl(1);
              normal_volume();
              // Clear all judgments
              over_event_flag = true;
              nuder_event_flag = true;
              normal_event_flag = VOLUME_CONTIUNE ? true : false;
              lv_led_off(ui_led1);
              lv_led_off(ui_led3);
            }
          }
          /*zero state set display */

          if (indicator_data.event[STATE_ZERO_EVENT] == STATE_ZERO_EVENT) {
            if (over_event_flag && nuder_event_flag && normal_event_flag) {
              over_event_flag = false;
              nuder_event_flag = false;
              normal_event_flag = false;
              led_1_ctrl(0);
              led_2_ctrl(0);
              led_3_ctrl(0);
              lv_led_off(ui_led1);
              lv_led_off(ui_led2);
              lv_led_off(ui_led3);
              // lv_event_send(ui_judge_color_ScreenPanel, LV_EVENT_CANCEL, NULL);
            }
          }

        }  // if the set value is 0, it is not counted.
      }    // trash_fileter_flag.
      break;
    case MODE_2:
      // LOGI(TAG, "current mode %d:", ui_data_ctx.curr_mode);
      if (trash_fileter_flag) {
        if (ui_data_ctx.ids == AMOUNT_VAL_E) {
          ui_data_ctx.ids = NONE_E;
          amount_weight_value = weight;
          lv_event_send(ui_data_ctx.obj, LV_EVENT_READY, NULL);
        }
        if (indicator_data.event[STATE_SIGN_EVENT] == STATE_SIGN_EVENT) {
          lv_label_set_text(ui_mode_2_scr_Panel1_Current_Weight_Label, "UNKNOWN");
          lv_label_set_text(ui_mode_2_scr_Panel1_Current_Count_Label, "\0");
        } else if (weight >= (float)100.0) {
          lv_label_set_text(ui_mode_2_scr_Panel1_Current_Weight_Label, "OVERLOAD");
          lv_label_set_text(ui_mode_2_scr_Panel1_Current_Count_Label, "\0");
        } else {
          lv_label_set_text(ui_mode_2_scr_Panel1_Current_Weight_Label, s_weight);
          if (amount_weight_value == 0.0) {
            lv_label_set_text(ui_mode_2_scr_Panel1_Current_Count_Label, "000");
          } else {
            lv_label_set_text(ui_mode_2_scr_Panel1_Current_Count_Label, s_amount_count);
          }
        }
      }
      break;
    default: break;
  }
}
///////////////////// SCREENS ////////////////////

void time_timer_cb(lv_timer_t *timer) {
  time_t t = time(NULL);
  struct tm *local = localtime(&t);

  sprintf(timeString, "%02d:%02d:%02d", local->tm_hour, local->tm_min, local->tm_sec);
  sprintf(dateString, "%04d-%02d-%02d", local->tm_year + 1900, local->tm_mon + 1, local->tm_mday);

  sprintf(time_date_string, "날짜 : %04d-%02d-%02d %02d:%02d:%02d", local->tm_year + 1900, local->tm_mon + 1,
          local->tm_mday, local->tm_hour, local->tm_min, local->tm_sec);

  OBJ_TEXT_SET_LABEL(ui_Time_Date_Set_Screen_Time_Label, timeString);
  OBJ_TEXT_SET_LABEL(ui_Time_Date_Set_Screen_Date_Label, dateString);
  OBJ_TEXT_SET_LABEL(ui_main_scr_Time_Date_Label, time_date_string);
}

void ui_init(void) {
  LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                            false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_main_screen_init();
  ui_device_id_reg_screen_init();
  ui_mode_2_screen_init();
  ui_Screen1_screen_init();
  ui_Screen2_screen_init();
  ui_list_select_screen_init();
  ui_judge_color_screen_init();
  ui_time_set_screen_init();
  // ui_indicator_model_select_screen_init();

  syscfg_get(CFG_DATA, "INDICATOR_MODEL", indicator_model_buf, sizeof(indicator_model_buf));
  if (strncmp(indicator_model_buf, "BX11", 4) == 0) {
    // zero command set
    weight_zero_command = baykon_bx11_zero_command;
    indicator_model = MODEL_BAYKON_BX11;
    OBJ_TEXT_SET_LABEL(ui_main_scr_Indicator_Model_Label, "모델 : BX11");
  } else if (strncmp(indicator_model_buf, "WTM-500", 7) == 0) {
    weight_zero_command = cas_zero_command;
    indicator_model = MODEL_CAD_WTM500;
    OBJ_TEXT_SET_LABEL(ui_main_scr_Indicator_Model_Label, "모델 : WTM-500");
  } else if (strncmp(indicator_model_buf, "none", 4) == 0) {
    indicator_model = MODEL_NONE;
    OBJ_TEXT_SET_LABEL(ui_main_scr_Indicator_Model_Label, "모델 : NONE");
  } else {
  }

  SET_MUX_CONTROL(CH_2_SET);

  ui_data_ctx.stack_root = NULL;
  ui_data_ctx.ptr[0] = &prod_num_value;
  ui_data_ctx.ptr[1] = &judge_total_count;
  ui_data_ctx.ptr[2] = &judge_over_count;
  ui_data_ctx.ptr[3] = &judge_normal_count;
  ui_data_ctx.ptr[4] = &judge_lack_count;

  lv_style_init(&style_clock);
  static uint32_t user_data = 10;
  lv_timer_t *logic_timer = lv_timer_create(logic_timer_cb, 10, &user_data);
  lv_timer_t *time_timer = lv_timer_create(time_timer_cb, 1000, user_data);

  // lv_disp_load_scr(ui_Screen1);
  lv_disp_load_scr(ui_Main_Screen);
}
