// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#ifndef _MS_TYPE_UI_H
#define _MS_TYPE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

#include <stdio.h>

void ui_main_screen_init(void);
extern lv_obj_t *ui_Main_Screen;
extern lv_obj_t *ui_MainScreenPanel;
void ui_event_MainScreenBtn1(lv_event_t *e);
extern lv_obj_t *ui_MainScreenBtn1;
extern lv_obj_t *ui_MainScreenBtn1Label;
extern lv_obj_t *ui_MainScreenBtn2;
extern lv_obj_t *ui_MainScreenBtn1Label2;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_led1;
extern lv_obj_t *ui_led2;
extern lv_obj_t *ui_led3;
void ui_event_Button1(lv_event_t *e);
extern lv_obj_t *ui_Button1;
void ui_event_Button4(lv_event_t *e);
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label_amount;
extern lv_obj_t *ui_Screen1_Prod_Num_Label;
extern lv_obj_t *ui_Screen1_Upper_Value_Label;
extern lv_obj_t *ui_Screen1_Lower_Value_Label;
void ui_event_Screen1_List_Select_Button(lv_event_t *e);

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui____initial_actions0;

// SCREEN: ui_list_select
void ui_list_select_screen_init(void);
extern lv_obj_t *ui_list_select;
extern lv_obj_t *ui_ListSelectScreen_List_Panel;
extern lv_obj_t *ui_ListSelectScreen_Comfirm_Panel;
extern lv_obj_t *ui_ListSelectScreen_Comfirm_Label;
extern lv_obj_t *ui_ListSelectScreen_Comfirm_Btn;
extern lv_obj_t *ui_ListSelectScreen_Comfirm_Btn_Label;
void ui_ListSelectScreen_Comfirm_Btn_e_handler(lv_event_t *e);
extern lv_obj_t *ui_ListSelectScreen_Delete_Btn;
extern lv_obj_t *ui_ListSelectScreen_Delete_Btn_Label;
void ui_ListSelectScreen_Delete_Btn_e_handler(lv_event_t *e);

extern float upper_weight_value;
extern float lower_weight_value;
extern int prod_num_value;
extern float renge_weight_value;
extern float amount_weight_value;

typedef struct textareas {
  lv_obj_t *ta1;
  lv_obj_t *ta2;
  lv_obj_t *ta3;
  // lv_obj_t *ta4;
  // lv_obj_t *ta5;
} textareas_t;

typedef enum {
  PROD_NUM_1 = 0x01,
  PROD_NUM_2,
  PROD_NUM_3,
  PROD_NUM_4,
  PROD_NUM_5,
  PROD_NUM_6,
  PROD_NUM_7,
  PROD_NUM_8,
  PROD_NUM_9,
  PROD_NUM_10,
  PROD_NUM_11,
  PROD_NUM_12,
  PROD_NUM_13,
  PROD_NUM_14,
  PROD_NUM_15,
  PROD_NUM_16,
  PROD_NUM_17,
  PROD_NUM_18,
  PROD_NUM_19,
} prod_num_t;

LV_FONT_DECLARE(ui_font_Display16);
LV_FONT_DECLARE(ui_font_Display24);
LV_FONT_DECLARE(ui_font_Display40);
LV_FONT_DECLARE(ui_font_Display90);
LV_FONT_DECLARE(NanumBar16);
LV_FONT_DECLARE(NanumBar18);
LV_FONT_DECLARE(NanumBar24);
LV_FONT_DECLARE(NanumBar32);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
