// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ms_type

#ifndef _MS_TYPE_UI_H
#define _MS_TYPE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_led1;
extern lv_obj_t *ui_led2;
extern lv_obj_t *ui_led3;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Keyboard1;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui____initial_actions0;

void textarea_event_handler(lv_event_t * e);
void textarea_event_handler1(lv_event_t * e);
void textarea_event_handler2(lv_event_t * e);

LV_FONT_DECLARE( ui_font_Display16);
LV_FONT_DECLARE( ui_font_Display24);
LV_FONT_DECLARE( ui_font_Display40);
LV_FONT_DECLARE( ui_font_Display90);
LV_FONT_DECLARE( NanumBar16);
LV_FONT_DECLARE( NanumBar18);
LV_FONT_DECLARE( NanumBar24);
LV_FONT_DECLARE( NanumBar32);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
