name: Build check irrigation hid

on:
  push:
    branches: [main]
    paths:
      - 'product/irrigation/hid/**'
  pull_request:
    branches: [main]
    paths:
      - 'product/irrigation/hid/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout irrigation hid
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: v5.0
        target: esp32s3
        path: './product/irrigation/hid'
