name: Build check irrigation child

on:
  push:
    branches: [main]
    paths:
      - 'product/irrigation/child/**'
  pull_request:
    branches: [main]
    paths:
      - 'product/irrigation/child/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout irrigation child
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: v5.0
        target: esp32
        path: './product/irrigation/child'
